### ISSUE TITLE
dx_ctl_users.pl imports delphix admin accounts as regular accounts

### ISSUE THREAD

**Issue by dbarkin** [delphix/dxtoolkit#10]
Error for release 2.3.1:
In release 2.3.0 - it works ok

if csv file like this:

C,user,user,user,user@site.net,,,,LDAP,"uid=user,ou=People,DC=CA,DC=DOMAIN",,Y,N

dx_ctl_users.pl imports delphix admin accounts as regular accounts

**Comment by pioro** [comment]
Hi,

That's weird - there is no changes between 2.3.0 and 2.3.1 code for that code.
I also check this with 5.1.3 engine and user was created as an admin user.

Could you please make sure you refreshed a browser after user was created and let me know if you can see still this issue ?

regards,
Marcin

**Comment by dbarkin** [comment]
moved to compiled version. Issue is gone.
