### ISSUE TITLE
Allow dx_ctl_users to set/clear apiUser property

### ISSUE THREAD

**Issue by tomsyth** [delphix/dxtoolkit#102]
Delphix users have a new property labeled 'apiUser' in the CLI. Please add functionality to dx_ctl_users to set or clear this property when manipulating users.

**Comment by teaboyteaboy** [comment]
This is blocking dx_ctl_users from being able to add users to at least SSO engines, if not all types of engines.  Error returned:

User <username> not created. Error: If you want to allow this user to authentication with local credentials, set the api user flag.

Thanks

**Comment by pioro** [comment]
it will be delivered with a new version
