### ISSUE TITLE
dxtoolkit command to disable and enable logsync

### ISSUE THREAD

**Issue by Satheeskodi** [delphix/dxtoolkit#109]
Need a dxtoolkit command to perform disable and enable logsync. Customer wants to turn off logsync as soon as the provisionable snapshot is created on the dSource.

**Comment by pioro** [comment]
this is already implemented

to disable logsync use:
dx_ctl_dsource -d 53 -action update -logsync no -dsourcename test121 

to enable logsync use:
dx_ctl_dsource -d 53 -action update -logsync yes -dsourcename test121
