### ISSUE TITLE
is there way for to find out which template was used to provision vDB

### ISSUE THREAD

**Issue by dbarkin** [delphix/dxtoolkit#11]
Hi Marcin,

is there way for to find out which template was used to provision vDB?

like list connecting vDB config templates to already provisioned vDBs

Thanks
Dmitri

**Comment by pioro** [comment]
Hi Dmitri,

If you will run dx_get_db_env with -config option it will display a VDB template in configuration column for every Oracle VDB

regards,
Marcin

**Comment by dbarkin** [comment]
Thank you.
