### ISSUE TITLE
dx_ctl_user csv output

### ISSUE THREAD

**Issue by akblackwel** [delphix/dxtoolkit#111]
We're attempting to automate user provisioning through the api's from an external source.

On thing I have to do is prepare a report. I'm extracting the users with dx_ctl_users.

One weird thing I'm seeing is duplicate users with different permissions.

So this is the mapping I think is correct.

User						admin_pr			js_user
Standard User					N					N
Engine Administrator			S					N
Self Service 					N					Y

My problem is I have an admin user

1 admin user
username         admin_pr			js_user
user1                     S                                     N         (Engine Administrator)
user1                     Y                                      N        (Self Service)

But then I'll have another user that is an admin that only has

username         admin_pr			js_user
user2                     S                                     N         (Engine Administrator)

I don't see other self-service permissions for other admins.

It seems inconstant.

Any thoughts?

Thanks.

**Comment by pioro** [comment]
Hi,

Delphix Engine has two different admin roles - sysadmin role and admin role.

dxtoolkit dx_get_users is mapping those roles inside a admin_pr column:
Y - is an admin role
S - is a sysadmin role
N - this is an ordinary user

In your 1st case - user1 has both roles - sysadmin and admin - and actually those users are created in different role namespaces so you will see one entry per role.

In the 2nd case user2has a sysadmin role but same user2 doesn't have an admin role but it has only Self-Service access.

One think to remember - if you are looking into GUI - you will see only admin role, ordinary users and self service users in admin part of GUI. The users with sysadmin role are displayed only in sysadmin part of GUI. Dxtoolkit can list users from both GUI in one report.

regards,
Marcin
