### ISSUE TITLE
Cannot change namespace we have different sources from different namespaces

### ISSUE THREAD

**Issue by jay8903** [delphix/dxtoolkit#112]
dx_provision_vdb Is there a way we can select replica namespaces during vdb provisioning?? currently there is no option like that for a provision vdb.. 

Another issue was cannot create a new container database for a vpdb i think script needs ammendments or let me know please

**Comment by pioro** [comment]
Hi,

You can select a source database from other namespace by specifying dbname@namespace.
All VDBs are always created in default namespace.

regards,
Marcin

**Comment by jay8903** [comment]
great that worked thank you very much
