### ISSUE TITLE
print selective columns from dx_get_db_env command

### ISSUE THREAD

**Issue by ankur3005** [delphix/dxtoolkit#113]
Hi,

I need to print only selective columns from the output of dx_get_db_env command.
Is there any argument or method to do that ?

All the columns do not fit on my putty screen and the output looks weird.
I just want few important columns to be printed to make it more meaningful.

Regards,
Ankur

**Comment by ankur3005** [comment]
Any updates please?

**Comment by pioro** [comment]
Hi,

There is no plan to add functionality to select columns to print.
You can use -format csv switch to display in CSV format and use awk or similar tool to select which columns you want to see on the screen.

regards,
Marcin

**Comment by ankur3005** [comment]
Thanks Marcin for replying.
-format csv did help, though I had to work little hard to list data in proper indentation :)
