### ISSUE TITLE
revoking a role (data, read, owner) from a user using dx_ctl_user 

### ISSUE THREAD

**Issue by dbarkin** [delphix/dxtoolkit#12]
not sure if it is possible:

when I'm removing a role from user_profiles CSV file (by removing the line with role or specifying None next to role) nothing happens.  

eg: 

Original setup 
user,group,dbgroupA,Data
user,group,dbgroupB,Data

Remove with None
user,group,dbgroupA,Data
user,group,dbgroupB,None <- Fails with not a valid value

Remove with deleting the line
user,group,dbgroupA,Data
<- nothing happens to dbgroupB permissions

Thanks

**Comment by pioro** [comment]
Thanks for opening this request. 

Marcin

**Comment by pioro** [comment]
Hi,

in 2.3.3-rc1 you can put None as a role name in profile file.

Remove with None
user,group,dbgroupA,Data
user,group,dbgroupB,None <- will remove any roles for user for dbgroupB


regards,
Marcin
