### ISSUE TITLE
dx_remove_db removes all VDBs if -type VDB and some switch is given. wrong switch need to be rejected instead of warning.

### ISSUE THREAD

**Issue by ajaytho** [delphix/dxtoolkit#121]
`./dx_remove_db -d dlpxengpri -type vdb -dbname vora2 -skip`
This deletes all VDBs. Accidently dbname switch was given instead of name.

For testing removed -skip

`./dx_remove_db -d dlpxengpri -type vdb -dbname vora2
Unknown option: dbname
Going to delete database - BreakFix / vora1
Are you sure (y/(n)) - use -skip to skip this confirmation 
`
It did detect wrong switch but still proceeded. when skip is given we won't have chance to see wrong switch was given and if skip is not given still might miss the text.

It would be good idea to reject the command if wrong switch is provided.

**Comment by pioro** [comment]
Fix for failing command for unknown parameters added.
I will be included in next release
