### ISSUE TITLE
issue creating an Oracle RAC environment with dx_create_env 

### ISSUE THREAD

**Issue by BUN1O** [delphix/dxtoolkit#125]
** Expected Behavior**
for creating the environment for oracle RAC ( -envtype rac ) , I am getting error :

** Actual Behavior**
Describe what actually happened.
-clustername xpd02 -debug
Dxtoolkit version 2.4.5
Loading engines from /delphix/dxtoolkit2/dxtools.conf
connecting to: HWYNFDPX03.SDI.CORP.BANKOFAMERICA.COM ( IP/name : 30.142.200.22 )
GET: https://30.142.200.22:443/resources/json/delphix/session
** GET https://30.142.200.22:443/resources/json/delphix/session ==> 200 OK
Session exists.
GET: https://30.142.200.22:443/resources/json/delphix/user/current
** GET https://30.142.200.22:443/resources/json/delphix/user/current ==> 200 OK
GET: https://30.142.200.22:443/resources/json/delphix/environment
** GET https://30.142.200.22:443/resources/json/delphix/environment ==> 200 OK
GET: https://30.142.200.22:443/resources/json/delphix/environment/oracle/clusternode
** GET https://30.142.200.22:443/resources/json/delphix/environment/oracle/clusternode ==> 200 OK
GET: https://30.142.200.22:443/resources/json/delphix/environment/windows/clusternode
** GET https://30.142.200.22:443/resources/json/delphix/environment/windows/clusternode ==> 200 OK
GET: https://30.142.200.22:443/resources/json/delphix/environment/user
** GET https://30.142.200.22:443/resources/json/delphix/environment/user ==> 200 OK (1s)
GET: https://30.142.200.22:443/resources/json/delphix/environment/oracle/listener
** GET https://30.142.200.22:443/resources/json/delphix/environment/oracle/listener ==> 200 OK
** POST https://30.142.200.22:443/resources/json/delphix/environment ==> 200 OK
Problem with job HASH(0x58cec40)

**Steps To Reproduce the Problem**
Describe in as much detail as possible how to reproduce the problem.

**Screenshots**

**Version**
Indicate the relevant versions of components. This may include the package version, operating system version, or other components relevant to the project.

**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by pioro** [comment]
Hello,

Is your Delphix Engine version 6.0 ? 

regards,
Marcin

**Comment by pioro** [comment]
Hello,

I understand an issue now and it will be resolved in the next release.

regards,
Marcin
