### ISSUE TITLE
"03112020: Enclose environment name in double quotes"

### ISSUE THREAD

**Issue by Jatinder-Luthra** [delphix/dxtoolkit#127]
**Is your feature request related to a problem? Please describe.**
Environment name with dx_get_env doesn't enclose the environment name in double-quotes, which is an issue for any environment name with spaces.

dx_get_env –d Landshark5 -backup /backupdir

**Describe the solution you'd like**
enclose environment name in double-quotes during extraction.

**Describe alternatives you've considered**
Manually adding double quotes but this impacts automation workflow

**Additional context**
N/A

**Comment by pioro** [comment]
fixed by Jatinder's PR
