### ISSUE TITLE
dx_get_capacity missing objects

### ISSUE THREAD

**Issue by johnsok0** [delphix/dxtoolkit#13]
Hi Marcin,

This morning the Delphix GUI shows 17.90TB used capacity on our 402 enigne, the dx_get_capacity csv extract indicates 10.2TB in used capacity.  There is a 7.70TB difference of capacity missing from the dx_get_capacity output.  

Some ideas:  HELD SPACE/NAMESPACE objects.  Our GUI indicates a total of 5.33TB for HELD SPACE and a total of 2.90TB for NAMESPACE, grand total for both objects is 8.23TB.  Not quite the 7.70TB as earlier indicated, but this is just an idea.  We use the SDD/REPLICATION between 2 engines for our PCI data.  

Thanks, Kate

![delphix_front_page_2017_02_17](https://cloud.githubusercontent.com/assets/22800993/23074144/2d5fbe14-f4f5-11e6-9010-66390771dcec.jpg)

**Comment by pioro** [comment]
New version of engine - 5.2 and newest toolkit is supporting this request now.

regards,
Marcin
