### ISSUE TITLE
"03142020: Script to get mapping of containers to datasources"

### ISSUE THREAD

**Issue by Jatinder-Luthra** [delphix/dxtoolkit#130]
**Is your feature request related to a problem? Please describe.**
This feature is very important to identify which container is mapped to which data source. 
`dx_get_js_datasource` provide information on template data source but not providing similar info for container names and data source.

**Describe the solution you'd like**
It will be good to have `dx_get_js_datasource` returned information about the container along with data source. For containers, right now the result shows N/A.

**Describe alternatives you've considered**
No alternatives identified, after analyzing multiple outputs of different dx_get_js_* scripts. No data or combination of data providing this info.

**Additional context**
N/A

**Comment by Jatinder-Luthra** [comment]
I updated the script `dx_get_js_datasource` with the below changes and I am able to get the container name.

```
  my $jsdatasources = new JS_datasource_obj ( $engine_obj , $template_obj, $db_obj);

  for my $ds (@{$jsdatasources->getJSDataSourceList()}) {

      my $temp_cont = $jstemplates->getName($jsdatasources->getJSTemplate($ds));

    ###### New code starts #######
      if ($temp_cont eq 'N/A') {

         $temp_cont = $jscontainers->getName($jsdatasources->getJSTemplate($ds));

       }
    ###### New code ends #######

      if (!defined($temp_cont)) {
        print "Not Defined","\n";
        next;
      }
```

Result before changes:
![image](https://user-images.githubusercontent.com/32877197/76694197-90204800-6646-11ea-8869-11dd72e08196.png)

Result after changes:
![image](https://user-images.githubusercontent.com/32877197/76694202-a3cbae80-6646-11ea-9f7e-beba14f9f870.png)

~Thanks

**Comment by Jatinder-Luthra** [comment]
A little bit of enhancement to identify if the self-service object is template or container.

```
  for my $ds (@{$jsdatasources->getJSDataSourceList()}) {

      my $temp_cont = $jstemplates->getName($jsdatasources->getJSTemplate($ds));

      my $type = "Template";

      if ($temp_cont eq 'N/A') {

         $temp_cont = $jscontainers->getName($jsdatasources->getJSTemplate($ds));

         $type = "Container";

       }
```

![image](https://user-images.githubusercontent.com/32877197/76694451-60bf0a80-6649-11ea-8191-667acb5a0055.png)

**Comment by pioro** [comment]
dx_get_js_container has a new parameter -listdb to display a VDB's used by container
Added in new release together with  -backup option for templates and container
