### ISSUE TITLE
"03142020: Handle priority number if self service template contain more than one source"

### ISSUE THREAD

**Issue by Jatinder-Luthra** [delphix/dxtoolkit#131]
**Is your feature request related to a problem? Please describe.**
If my self-service template contains more than one source, `dx_get_js_template` and `dx_ctl_js_template` scripts are not taking care of priority and not able to add more than one data source using dx_ctl_js_template.

**Describe the solution you'd like**
Enhancement of `dx_get_js_template` and `dx_ctl_js_template `scripts to extract template info with priority and create templates having more than one data source with different priorities.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pioro** [comment]
Added in new release as -backup option for templates and container including a priority number for templates
