### ISSUE TITLE
Make dx_ctl_dsource perform updates at the group level

### ISSUE THREAD

**Issue by nstack21** [delphix/dxtoolkit#135]
It would be great if dx_ctl_dsource could be updated to work by using the group option rather than forcing the individual dSource name. For example:
```
$ dx_ctl_dsource -type sybase -group "ASE dSource" -action update -validatedsync DISABLED
Options  -dsourcename is required to detach or update. 
```
This would help users in the scenarios where they need to make mass configuration changes to a bunch of ASE or SQL Server dSources.

**Comment by pioro** [comment]
it will be part of next release
