### ISSUE TITLE
[2020/04/15] toolkit raises warnings when executed by anonymous user in Linux Containers

### ISSUE THREAD

**Issue by DSTOLF** [delphix/dxtoolkit#138]
** Expected Behavior**
Some container platforms, like OpenShift, enforce anonymous users in running container. Inside the Dockerfile, the running user id is changed to 1001, but there's no such user created.

Running the toolkit inside such container shouldn't be an issue.

** Actual Behavior**

Every command raises an warning about NULL concatenation in a string.

This causes `getpwuid` to return `null` [here](https://github.com/delphix/dxtoolkit/blob/bbd67fd5d2f6766e3614567b7a9fdbf05c5f6e91/lib/POSIX_osuser.pm#L26) , which will then raise an error [here](https://github.com/delphix/dxtoolkit/blob/bbd67fd5d2f6766e3614567b7a9fdbf05c5f6e91/lib/Engine.pm#L544), when trying to concatenate NULL into the cookie name string.

**Steps To Reproduce the Problem**
Build a dxtoolkit container with anonymous user, run any command.

**Comment by pioro** [comment]
fixed in 2.4.7
