### ISSUE TITLE
"20-APR-2020 Cannot create SSO user with no Password"

### ISSUE THREAD

**Issue by Ranzo3** [delphix/dxtoolkit#139]
** Expected Behavior**
Tried to create a NATIVE user with dx_ctl_user on an Engine connected to Centralized Management.  Since the Engine was using SSO, it should've allowed me to create a user with no password, as long as they weren't an API user.  (Further testing needed with Admin user on/off, since this can affect the API flag).

** Actual Behavior**
-Entering User_obj::getName
-Entering User_obj::getName
 -resources/json/delphix/user
-Entering Engine::postJSONData
-{"lastName":"Graeul","apiUser":false,"type":"User","emailAddress":"jason.graeul@delphix.com","credential":{"password":"xxxxx","type":"PasswordCredential"},"authenticationType":"NATIVE","sessionTimeout":60,"name":"jgrauel","firstName":"Jason"}
** POST https://54.190.81.183:443/resources/json/delphix/user ==> 200 OK
 -Response message: {
   "type" : "ErrorResult",
   "status" : "ERROR",
   "error" : {
      "diagnoses" : null,
      "type" : "APIError",
      "commandOutput" : null,
      "id" : "exception.validation.bad.input",
      "details" : {
         "credential" : {
            "password" : {
               "commandOutput" : null,
               "diagnoses" : null,
               "id" : "exception.validation.string.tooshort",
               "details" : "The string must contain at least 1 characters.",
               "action" : null
            }
         }
      },
      "action" : "Check your input parameters and try again."
   }
}

 -Check your input parameters and try again.
User jgrauel not created. Error: Check your input parameters and try again.

**Steps To Reproduce the Problem**
user.csv

#command, username, firstname, lastname, email, workphone, homephone, mobilephone, authtype, principal, password, admin_priv, js_user, timeout, apiUser
#Fails because Native user with no Password, with apiUser=N
#C,jgrauel,Jason,Graeul,jason.graeul@delphix.com,,,,NATIVE,,,Y,N,60,N
#Fails because Native user with no Password, with apiUser=N and admin_priv=N
#C,jgrauel,Jason,Graeul,jason.graeul@delphix.com,,,,NATIVE,,,N,N,60,N
#Works
C,jgrauel,Jason,Graeul,jason.graeul@delphix.com,,,,NATIVE,,password123,Y,N,60,Y

**Screenshots**

**Version**
2.4.6.1

**Additional Context**
Low priority, since few engines are on SSO and a workaround is available.
You can create an SSO user as long as you provide an email and a password.
Most customers can probably create them with a password even if it is isn't used.

**Comment by pioro** [comment]
it will be fixed in 2.4.7
