### ISSUE TITLE
DxToolkit v.2.3.1 sends 0/True last exe status/lastexit code on error

### ISSUE THREAD

**Issue by khrystle** [delphix/dxtoolkit#14]
When I purposely cause an error in the dx_ctl_db.exe, for example trying to stop a non-existent database or environment, the dx toolkit throws 0/True rather than an error code. Because of this I can't stop my powershell process to exit the code unless I try to parse the log file.

Simple one line picture, here:

![dxtoolkiterror0true](https://cloud.githubusercontent.com/assets/26656140/24303383/c01443d4-1083-11e7-8cb1-22fbfc9a9b4d.JPG)

**Comment by pioro** [comment]
Hi,

Could you please confirm that you are using version 2.3.1 of dxtoolkit ?

Also could you please run your command without start-process ?

when I run it from cmd.exe I got this message

C:\Program Files\Delphix\DxToolkit2>dx_ctl_db.exe -d Landshark51 -name nonex -action stop
There is no DB selected to process on Landshark51 . Please check filter definitions.

C:\Program Files\Delphix\DxToolkit2>echo %errorlevel%
1

regards,
Marcin

**Comment by pioro** [comment]
Same command run from Power shell

PS C:\Program Files\Delphix\DxToolkit2> Set-PSDebug -trace 2;
DEBUG:    1+  <<<< Set-PSDebug -trace 2;
DEBUG:    2+         $foundSuggestion = <<<<  $false
DEBUG:     ! SET $foundSuggestion = 'False'.
DEBUG:    4+         if <<<< ($lastError -and
DEBUG:   15+         $foundSuggestion <<<<
PS C:\Program Files\Delphix\DxToolkit2>
PS C:\Program Files\Delphix\DxToolkit2>
PS C:\Program Files\Delphix\DxToolkit2> .\test.ps1
DEBUG:    1+  <<<< .\test.ps1
DEBUG:     ! CALL function 'test.ps1'  (defined in file 'C:\Program Files\Delphix\DxToolkit2\test.ps1')
DEBUG:    1+  <<<< &  "C:\Program Files\Delphix\DxToolkit2\dx_ctl_db.exe" -d Landshark51 -name nonexist -type VDB
-action stop
There is no DB selected to process on Landshark51 . Please check filter definitions.
DEBUG:    2+ $LASTEXITCODE <<<<
1
DEBUG:    2+         $foundSuggestion = <<<<  $false
DEBUG:     ! SET $foundSuggestion = 'False'.
DEBUG:    4+         if <<<< ($lastError -and
DEBUG:   15+         $foundSuggestion <<<<
PS C:\Program Files\Delphix\DxToolkit2>

regards,
Marcin

**Comment by pioro** [comment]
Here is one more example of PowerShell

$p = Start-Process -FilePath "C:\Program Files\Delphix\DxToolkit2\dx_ctl_db.exe" -ArgumentList " -d Landshark51 -name nonexist -type VDB -action stop" -Wait -NoNewWindow -PassThru
echo "Exit code " $p.ExitCode

You need to add "-NoNewWindow -PassThru" to get a exit code from process and display it using $p.ExitCode

regards,
Marcin

**Comment by khrystle** [comment]
Hi Marcin,

When I run it I get error messages but I end up with True/0 for error codes, showing success. I think there is some reason I had to use the Start-Process to run this because we are trying to automate it with another tool but I will look to see if I can get around that somehow. Because the error messages were different, I didn’t see anything I could reliably hook onto (like if they all started with “ERROR:” or something.

I’ll try the suggestions from your emails out and get back to you.

Thank you for your help!

~Khrystle.

**Comment by khrystle** [comment]
Thank you, Marcin. We were able to get this working.

~Khrystle.
