### ISSUE TITLE
"[2020-04-23]: [Ability to backup  masked VDBs metadata]"

### ISSUE THREAD

**Issue by Jatinder-Luthra** [delphix/dxtoolkit#140]
**Is your feature request related to a problem? Please describe.**
`dx_get_db_env -backup` is not backing up masked VDBs with masking job. During restore, they get created as regular VDBs. 

**Describe the solution you'd like**
Add `-maskingjob or -maskedbyscript` for masked VDBs in backup scripts.

**Describe alternatives you've considered**
Manually update backup scripts with `-maskingjob or -maskedbyscript` for masked VDBs.

**Additional context**
N/A

**Comment by pioro** [comment]
it will be included in 2.4.7
