### ISSUE TITLE
"12-MAY-2020" dx_ctl_analytics help POD bug

### ISSUE THREAD

**Issue by Ranzo3** [delphix/dxtoolkit#144]
** Expected Behavior**
No POD Error

** Actual Behavior**
    Display collectors specified as a comma separated list

     dx_ctl_analytics -d Landshark5 -action display -type cpu,disk,nfs
     Connected to Delphix Engine Landshark5 (IP 172.16.180.131)
     Engine         Analytic   State    Axes
     -------------- ---------- -------- -------------------------------------------------------
     Landshark5     cpu        RUNNING  idle,user,kernel
     Landshark5     disk       RUNNING  latency,avgLatency,throughput,count,op
     Landshark5     nfs        RUNNING  latency,throughput,count,op

POD ERRORS
    Hey! The above document had some coding errors, which are explained
    below:

    Around line 60:
        You forgot a '=back' before '=head1'

**Steps To Reproduce the Problem**
dx_ctl_analytics --help

**Version**
2.4.6.1

**Comment by pioro** [comment]
it will be fixed in 2.4.7
