### ISSUE TITLE
dx_ctl_engine_upgrade: upload filename checks fail for 6.x upgrade files

### ISSUE THREAD

**Issue by stu-williams** [delphix/dxtoolkit#146]
** Expected Behavior**
The upgrade file should have been uploaded to all engines

** Actual Behavior**
Internal validation of the filename failed, an error was reported and no actions taken

**Steps To Reproduce the Problem**
Describe in as much detail as possible how to reproduce the problem.

$ ./dx_ctl_engine_upgrade -all -action upload -filename Delphix_6.0.2.0_2020-05-05-20-11_Standard_Upgrade.tar -debug
Dxtoolkit version 2.4.6.1
Loading engines from dxtools.conf
Filename is not matching delphix upgrade pattern 

**Screenshots**
n/a

**Version**
dxtoolkit 2.4.6.1, Mac OS X Catalina 10.15.4 (also Windows)

**Additional Context**

The filename format has changed a little with the 6.x upgrade images, being .tar not tar.gz and going from "upgrade" to "Standard_Upgrade"

**Comment by pioro** [comment]
It will be released in 2.4.7
