### ISSUE TITLE
"[04/06/2020] [Can't use string ("NA") as a HASH ref while "strict refs" in use at /tmp/par-6f7261636c65/cache-8e053051c39adb8a9bd4e8737acd17f3d9a2b626/inc/lib/OracleVDB_obj.pm line 445]"

### ISSUE THREAD

**Issue by ankur3005** [delphix/dxtoolkit#148]
** Expected Behavior**
The script should list all targets.
delphix/dxtoolkit2.3.8.1/dxtoolkit2/dx_get_instance

** Actual Behavior**
However , it is failing with below error.

Can't use string ("NA") as a HASH ref while "strict refs" in use at /tmp/par-6f7261636c65/cache-8e053051c39adb8a9bd4e8737acd17f3d9a2b626/inc/lib/OracleVDB_obj.pm line 445

**Version**
dxtoolkit2.3.8.1

**Additional Context**
This used to work smoothly, however it is not working as expected

**Comment by pioro** [comment]
Hello,

It can be related to CDB/PDB configuration or detached dSource.
Could you please upgrade Dxtoolkit to the 2.4.6.1 version and check again ?

regards,
Marcin
