### ISSUE TITLE
dx_ctl_js_bookmarks appends date to bookmark name specified

### ISSUE THREAD

**Issue by stu-williams** [delphix/dxtoolkit#149]
** Expected Behavior**
The bookmark name should have been set to the value passed in via the  -bookmark_name flag

** Actual Behavior**
The bookmark name was appended with a date string

**Steps To Reproduce the Problem**

$ ./dx_ctl_js_bookmarks -action create -template_name Master -bookmark_name "HK 2020-06-11" -source master -snapshots last                                    
Starting job JOB-48 for bookmark HK 2020-06-11-2020-06-11 13:58:21.
5 - 100
Job JOB-48 finished with state: COMPLETED

The "-06-11 13:58:21." has been appended changing the bookmark name.

**Screenshots**
n/a

**Version**
2.4.6.1 (was running it on Solaris 11 x64)

**Additional Context**

**Comment by pioro** [comment]
Hi,

This is an expected behaviour if you are creating a bookmark in template using -snapshot last option. Bookmark name is a prefix to a full bookmark name which will be a prefix plus snapshot date.

**Comment by stu-williams** [comment]
Hello

The man page/help describes "-bookmark_name bookmark_name Set bookmark name" so the expectation was the string specified would be used. The date at which the bookmark is created may not be meaningful, could even be confusing when it differs to the point in time it represents. 

As this is not a bug then I would like to request that the command is enhanced to enable a bookmark to be able to be created named only by the string specified.
