### ISSUE TITLE
"09/2/2020. [0x42b6270]"

### ISSUE THREAD

**Issue by BUN1O** [delphix/dxtoolkit#155]
** Expected Behavior**
dx_create_env is NOT working for Oracle RAC cluster environment. Is their any issue?
** Actual Behavior**
Ran the command with all necessary parameter but it failed. Ran with "-debug" option got Problem with job HASH(0x42b6270)

Same command from same location was successfull NON-Cluster environment

**Steps To Reproduce the Problem**
Describe in as much detail as possible how to reproduce the problem.

I can open a Delphix Support ticket to upload all errors, if that helps.
**Screenshots**

**Version**
Indicate the relevant versions of components. This may include the package version, operating system version, or other components relevant to the project.

Version 2.3.8.1
**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by pioro** [comment]
Hello,

Similar issue was fixed in the in version 2.4.6
Please upgrade to the latest version of dxtoolkit and check again.
