### ISSUE TITLE
"01/25/2021 dx_set_envpass fails on windows environment"

### ISSUE THREAD

**Issue by tomsyth** [delphix/dxtoolkit#167]
** Expected Behavior**
Expect password for environment user to be updated.

** Actual Behavior**
Failure - appears to be checking ssh connectivity then reports that credentials are not valid.

**Steps To Reproduce the Problem**
Call dx_set_envpass on a windows environment.

**Screenshots**

**Version**
lastest release - 2.4.10

**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by marcinops** [comment]
Fixed in 2.4.11
