### ISSUE TITLE
"[23-MAR-2021] [dx_set_dbpass [ -engine|d <delphix identifier> | -all ] [ -configfile file ][ -group group_name | -dbname db_name | -host host_name | -type dsource|vdb ] [-username <username>] -password <password> [ --help|? ] [ -debug ]"

### ISSUE THREAD

**Issue by Jgadelphix** [delphix/dxtoolkit#176]
** Expected Behavior**
the db password should have been changed

** Actual Behavior**
the db password is not changed and the following error is being displayed.  It is complaining about a parameter that does not exist in the syntax of the command
ex:
D:\dxtoolkit2-v2.4.8-win64-installer\dxtoolkit2>dx_set_dbpass -d delphixenginecollector -group MSSQL_TEST -dbname "FX" -username svc_delphixdb_prod -password Password2
MS SQL database user type is now required
Password check failed.
Username or password is invalid.
Problem with setting password
 **Steps To Reproduce the Problem**
just type the command replacing the parameters by their values
1. Go to '. your dxtoolkit drectory'
2. run the following command : dx_set_dbpass -d <Engine_name>  -group <group_name> -dbname "<db_name>" -username <username> -password <password_name>
3. . Scroll down to '....'
MS SQL database user type is now required
Password check failed.
Username or password is invalid.
Problem with setting password**Screenshots**

**Version**
dxtoolkit version 2.4.8
**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by Ranzo3** [comment]
**Steps To Reproduce the Problem**
Attempting to change the DB Password for an already existing user

**Version**
It worked in version of Delphix 5.3.8.1 version but not working with latest delphix 6.0.6.1 version.  Probably a breaking change in the API.

**Comment by Ranzo3** [comment]
Hypothesis (not proven):   this is part of new change with option to create dSource using db user or os user, which was previously only db user.

**Comment by Jgadelphix** [comment]
Good Evening Ranzo,
How are you?  I was just about to post something on the TS channel as I did not want to annoy you with an email, because Michael took told ne that you answered to the post from Himanshu @OTPP, so I know you were interested in the solution:

Marcin and I worked on the issue together today and me with the customer ( did not want to create a lab for this lol!)
We found out that the issue was the 6.0.0.0 + API and what we did, is exactly what you suggested in the previous email.
So Marcin asked  me file the issue and we corrected it the following way:

  1.  As the customer, OTPP ,   has both 5.3.8.1 and 6.0.0.1 engines, I had him run the commands on both.
  2.  It succeeded on the 5.3.8.1 and failed on the 6.0.0.1 engine.
  3.  So , we knew that the API was the culprit.  So we ran it with the “ -dever 5.3”  and it worked!
Thanks
JG
From: Ranzo J Taylor, III ***@***.***>
Date: Tuesday, March 23, 2021 at 16:42
To: delphix/dxtoolkit ***@***.***>
Cc: Jgadelphix ***@***.***>, Author ***@***.***>
Subject: Re: [delphix/dxtoolkit] "[23-MAR-2021] [dx_set_dbpass [ -engine|d <delphix identifier> | -all ] [ -configfile file ][ -group group_name | -dbname db_name | -host host_name | -type dsource|vdb ] [-username <username>] -password <password> [ --help|? ] [...

Hypothesis (not proven): this is part of new change with option to create dSource using db user or os user, which was previously only db user.

**Comment by Jgadelphix** [comment]
Here is the command that we ran today with the -dever option :
D:\dxtoolkit2-v2.4.8-win64-installer\dxtoolkit2>dx_set_dbpass -d delphixengcollector1 -group Testing_Group -dbname FX -username svc_delphixdb_prod -password Password2 -debug -dever 5.3
Dxtoolkit version 2.4.8
Loading engines from D:/dxtoolkit2-v2.4.8-win64-installer/dxtoolkit2/dxtools.conf
Can’t secure cookie. Windows machine
connecting to: delphixengcollector1 ( IP/name : 172.21.96.51 )
GET: http://172.21.96.51:80/resources/json/delphix/session<http://172.21.96.51/resources/json/delphix/session>
** GET http://172.21.96.51:80/resources/json/delphix/session<http://172.21.96.51/resources/json/delphix/session> ==> 200 OK
API Version: 1.10
** POST http://172.21.96.51:80/resources/json/delphix/session<http://172.21.96.51/resources/json/delphix/session> ==> 200 OK
** POST http://172.21.96.51:80/resources/json/delphix/login<http://172.21.96.51/resources/json/delphix/login> ==> 200 OK (1s)
login to 172.21.96.51 succeeded.
GET: http://172.21.96.51:80/resources/json/delphix/source<http://172.21.96.51/resources/json/delphix/source>
** GET http://172.21.96.51:80/resources/json/delphix/source<http://172.21.96.51/resources/json/delphix/source> ==> 200 OK (3s)
GET: http://172.21.96.51:80/resources/json/delphix/sourceconfig<http://172.21.96.51/resources/json/delphix/sourceconfig>
** GET http://172.21.96.51:80/resources/json/delphix/sourceconfig<http://172.21.96.51/resources/json/delphix/sourceconfig> ==> 200 OK (4s)
GET: http://172.21.96.51:80/resources/json/delphix/repository<http://172.21.96.51/resources/json/delphix/repository>
** GET http://172.21.96.51:80/resources/json/delphix/repository<http://172.21.96.51/resources/json/delphix/repository> ==> 200 OK
GET: http://172.21.96.51:80/resources/json/delphix/environment<http://172.21.96.51/resources/json/delphix/environment>
** GET http://172.21.96.51:80/resources/json/delphix/environment<http://172.21.96.51/resources/json/delphix/environment> ==> 200 OK (1s)
GET: http://172.21.96.51:80/resources/json/delphix/environment/oracle/clusternode<http://172.21.96.51/resources/json/delphix/environment/oracle/clusternode>
** GET http://172.21.96.51:80/resources/json/delphix/environment/oracle/clusternode<http://172.21.96.51/resources/json/delphix/environment/oracle/clusternode> ==> 200 OK
GET: http://172.21.96.51:80/resources/json/delphix/environment/windows/clusternode<http://172.21.96.51/resources/json/delphix/environment/windows/clusternode>
** GET http://172.21.96.51:80/resources/json/delphix/environment/windows/clusternode<http://172.21.96.51/resources/json/delphix/environment/windows/clusternode> ==> 200 OK (1s)
GET: http://172.21.96.51:80/resources/json/delphix/environment/user<http://172.21.96.51/resources/json/delphix/environment/user>
** GET http://172.21.96.51:80/resources/json/delphix/environment/user<http://172.21.96.51/resources/json/delphix/environment/user> ==> 200 OK
GET: http://172.21.96.51:80/resources/json/delphix/environment/oracle/listener<http://172.21.96.51/resources/json/delphix/environment/oracle/listener>
** GET http://172.21.96.51:80/resources/json/delphix/environment/oracle/listener<http://172.21.96.51/resources/json/delphix/environment/oracle/listener> ==> 200 OK (1s)
GET: http://172.21.96.51:80/resources/json/delphix/host<http://172.21.96.51/resources/json/delphix/host>
** GET http://172.21.96.51:80/resources/json/delphix/host<http://172.21.96.51/resources/json/delphix/host> ==> 200 OK (1s)
GET: http://172.21.96.51:80/resources/json/delphix/namespace<http://172.21.96.51/resources/json/delphix/namespace>
** GET http://172.21.96.51:80/resources/json/delphix/namespace<http://172.21.96.51/resources/json/delphix/namespace> ==> 200 OK
GET: http://172.21.96.51:80/resources/json/delphix/toolkit<http://172.21.96.51/resources/json/delphix/toolkit>
** GET http://172.21.96.51:80/resources/json/delphix/toolkit<http://172.21.96.51/resources/json/delphix/toolkit> ==> 200 OK
GET: http://172.21.96.51:80/resources/json/delphix/database<http://172.21.96.51/resources/json/delphix/database>
** GET http://172.21.96.51:80/resources/json/delphix/database<http://172.21.96.51/resources/json/delphix/database> ==> 200 OK (2s)
GET: http://172.21.96.51:80/resources/json/delphix/namespace<http://172.21.96.51/resources/json/delphix/namespace>
** GET http://172.21.96.51:80/resources/json/delphix/namespace<http://172.21.96.51/resources/json/delphix/namespace> ==> 200 OK
GET: http://172.21.96.51:80/resources/json/delphix/group<http://172.21.96.51/resources/json/delphix/group>
** GET http://172.21.96.51:80/resources/json/delphix/group<http://172.21.96.51/resources/json/delphix/group> ==> 200 OK
** POST http://172.21.96.51:80/resources/json/delphix/sourceconfig/MSSQL_SINGLE_CONFIG-249/validateCredentials<http://172.21.96.51/resources/json/delphix/sourceconfig/MSSQL_SINGLE_CONFIG-249/validateCredentials> ==> 200 OK (1s)
** POST http://172.21.96.51:80/resources/json/delphix/sourceconfig/MSSQL_SINGLE_CONFIG-249<http://172.21.96.51/resources/json/delphix/sourceconfig/MSSQL_SINGLE_CONFIG-249> ==> 200 OK
Password has been set.D:\dxtoolkit2-v2.4.8-win64-installer\dxtoolkit2>dx_set_dbpass -d delphixenginecollector -group MSSQL_TEST -dbname FX -username svc_delphixdb_prod -password Password2 -debug -dever 5.3
Dxtoolkit version 2.4.8
Loading engines from D:/dxtoolkit2-v2.4.8-win64-installer/dxtoolkit2/dxtools.conf
Can’t secure cookie. Windows machine
connecting to: delphixenginecollector ( IP/name : 10.254.222.11 )
calling $VAR1 = bless( do{\(my $o = ’https://delphix.okta.com/oauth2/default/v1/token')<https://delphix.okta.com/oauth2/default/v1/token')>}, ‘URI::https’ );
$VAR2 = 2;** POST http://10.254.222.11:80/sso/virtualization/api/login<http://10.254.222.11/sso/virtualization/api/login> ==> 200 OK
token login to 10.254.222.11 succeeded.
GET: http://10.254.222.11:80/resources/json/delphix/source<http://10.254.222.11/resources/json/delphix/source>
** GET http://10.254.222.11:80/resources/json/delphix/source<http://10.254.222.11/resources/json/delphix/source> ==> 200 OK (1s)
GET: http://10.254.222.11:80/resources/json/delphix/sourceconfig<http://10.254.222.11/resources/json/delphix/sourceconfig>
** GET http://10.254.222.11:80/resources/json/delphix/sourceconfig<http://10.254.222.11/resources/json/delphix/sourceconfig> ==> 200 OK (1s)
GET: http://10.254.222.11:80/resources/json/delphix/repository<http://10.254.222.11/resources/json/delphix/repository>
** GET http://10.254.222.11:80/resources/json/delphix/repository<http://10.254.222.11/resources/json/delphix/repository> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/environment<http://10.254.222.11/resources/json/delphix/environment>
** GET http://10.254.222.11:80/resources/json/delphix/environment<http://10.254.222.11/resources/json/delphix/environment> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/environment/oracle/clusternode<http://10.254.222.11/resources/json/delphix/environment/oracle/clusternode>
** GET http://10.254.222.11:80/resources/json/delphix/environment/oracle/clusternode<http://10.254.222.11/resources/json/delphix/environment/oracle/clusternode> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/environment/windows/clusternode<http://10.254.222.11/resources/json/delphix/environment/windows/clusternode>
** GET http://10.254.222.11:80/resources/json/delphix/environment/windows/clusternode<http://10.254.222.11/resources/json/delphix/environment/windows/clusternode> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/environment/user<http://10.254.222.11/resources/json/delphix/environment/user>
** GET http://10.254.222.11:80/resources/json/delphix/environment/user<http://10.254.222.11/resources/json/delphix/environment/user> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/environment/oracle/listener<http://10.254.222.11/resources/json/delphix/environment/oracle/listener>
** GET http://10.254.222.11:80/resources/json/delphix/environment/oracle/listener<http://10.254.222.11/resources/json/delphix/environment/oracle/listener> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/host<http://10.254.222.11/resources/json/delphix/host>
** GET http://10.254.222.11:80/resources/json/delphix/host<http://10.254.222.11/resources/json/delphix/host> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/namespace<http://10.254.222.11/resources/json/delphix/namespace>
** GET http://10.254.222.11:80/resources/json/delphix/namespace<http://10.254.222.11/resources/json/delphix/namespace> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/toolkit<http://10.254.222.11/resources/json/delphix/toolkit>
** GET http://10.254.222.11:80/resources/json/delphix/toolkit<http://10.254.222.11/resources/json/delphix/toolkit> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/database<http://10.254.222.11/resources/json/delphix/database>
** GET http://10.254.222.11:80/resources/json/delphix/database<http://10.254.222.11/resources/json/delphix/database> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/namespace<http://10.254.222.11/resources/json/delphix/namespace>
** GET http://10.254.222.11:80/resources/json/delphix/namespace<http://10.254.222.11/resources/json/delphix/namespace> ==> 200 OK
GET: http://10.254.222.11:80/resources/json/delphix/group<http://10.254.222.11/resources/json/delphix/group>
** GET http://10.254.222.11:80/resources/json/delphix/group<http://10.254.222.11/resources/json/delphix/group> ==> 200 OK
** POST http://10.254.222.11:80/resources/json/delphix/sourceconfig/MSSQL_SINGLE_CONFIG-202/validateCredentials<http://10.254.222.11/resources/json/delphix/sourceconfig/MSSQL_SINGLE_CONFIG-202/validateCredentials> ==> 200 OK
** POST http://10.254.222.11:80/resources/json/delphix/sourceconfig/MSSQL_SINGLE_CONFIG-202<http://10.254.222.11/resources/json/delphix/sourceconfig/MSSQL_SINGLE_CONFIG-202> ==> 200 OK
Password has been set.

Thanks

JG

From: Ranzo J Taylor, III ***@***.***>
Date: Tuesday, March 23, 2021 at 15:26
To: delphix/dxtoolkit ***@***.***>
Cc: Jgadelphix ***@***.***>, Author ***@***.***>
Subject: Re: [delphix/dxtoolkit] "[23-MAR-2021] [dx_set_dbpass [ -engine|d <delphix identifier> | -all ] [ -configfile file ][ -group group_name | -dbname db_name | -host host_name | -type dsource|vdb ] [-username <username>] -password <password> [ --help|? ] [...

Steps To Reproduce the Problem
Attempting to change the DB Password for an already existing user

Version
It worked in version of Delphix 5.3.8.1 version but not working with latest delphix 6.0.6.1 version. Probably a breaking change in the API.

**Comment by marcinops** [comment]
There was a problem with validating password call inside dxtoolkit.
Fixed in version 2.4.11
