### ISSUE TITLE
"24032021 - vfiles snapshot doesn't work with 6.0.7"

### ISSUE THREAD

**Issue by pioro** [delphix/dxtoolkit#177]
** Expected Behavior**
dx_snapshot_db should take a snapshot of vfiles

** Actual Behavior**
Failing with API error of missing mandatory parameter
Problem with starting job

Error: parameters->The field "parameters" is required.

**Steps To Reproduce the Problem**
run dx_snapshot_db

**Comment by Jgadelphix** [comment]
try to use the same command with the -dever 5.3

**Comment by marcinops** [comment]
Fixed in 2.4.11 - also dSource creation for vfiles fixed
Resync flag added to dx_snapshot_db to support vFiles in addition to DB2
