### ISSUE TITLE
"April 6th 2021: Not able to provision vDBs while adding powershell hooks from a hook template"

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/dxtoolkit#179]
** Expected Behavior**
By using dx_provision_vdb binary, we should be able to add any hook from a hook template(whether are bash or expect or ps).

** Actual Behavior**
Tested in a local lab provisioning a MSSQL vDB and assigning a hook from a hook template(powershell) but this does not work.

Dxtoolkit command executed:

./dx_provision_vdb -d carlosidb.dlpxdc.co -group targets_carlos -sourcename Soda -targetname VDB1 -dbname VDB1  -environment carloswintgt -type mssql -envinst MSSQLSERVER  -timestamp LATEST_SNAPSHOT -configureclone TESTHOOK,hooktemplate,PS -

When enabling debug mode, noticed that this command was trying to add a BASH hook which can't be added since its a MSSQL vDB:

   "source" : {
      "operations" : {
         "type" : "VirtualSourceOperations",
         "configureClone" : [
            {
               "command" : "echo test\r\nexit 0",
               "type" : "RunBashOnSourceOperation",
               "name" : "TESTHOOK"
            }
         ]

Using dx_provision_vdb and using a powershell script to add a hook works fine.

**Version**
Tested in 2.4.9

**Comment by marcinops** [comment]
fixed in 2.4.11 - Default PS mode added
