### ISSUE TITLE
"[30-Jul-2021] [dx-ctl-dsource]"

### ISSUE THREAD

**Issue by Jgadelphix** [delphix/dxtoolkit#186]
** Expected Behavior**
When we dsource any MSSQL database via GUI, we have an option to enable Commvault ingestion and, option to provide commserver hostname.
But we don’t see an option to mention the commserve hostname when we try to run dsource via CLI (through dxtoolkit) and getting below error message, 
Error message: Commvault is not configured for dSource "Admin".
** Actual Behavior**
Error message: Commvault is not configured for dSource "Admin".

**Steps To Reproduce the Problem**
dx_ctl_dsource -d delphixengcollector1 -type mssql -sourcename Admin -sourceinst MSSQLSERVER -sourceenv DBAPWD0171748N1 -source_os_user svcdelphixprod -dbuser svc_delphixdb_prod -password evEpl4Dd -group Testing_Group -dsourcename Admin -stage_os_user "otppb\svcdelphixnonprod" -stageinst MSSQLSERVER -stageenv delsqlstg07 -logsync yes -validatedsync FULL_OR_DIFFERENTIAL -action create
Engine: Delphixengcollector1

1. dx_ctl_dsource -d delphixengcollector1 -type mssql -sourcename Admin -sourceinst MSSQLSERVER -sourceenv DBAPWD0171748N1 -source_os_user svcdelphixprod -dbuser svc_delphixdb_prod -password evEpl4Dd -group Testing_Group -dsourcename Admin -stage_os_user "otppb\svcdelphixnonprod" -stageinst MSSQLSERVER -stageenv delsqlstg07 -logsync yes -validatedsync FULL_OR_DIFFERENTIAL -action create
Engine: Delphixengcollector1

**Screenshots**

**Version**
version 5.3.8 and 6.0.8.0

**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by marcinops** [comment]
Commited in 2.4.13-prebuild - for tests
