### ISSUE TITLE
unable to connect to delphix engine using dxtoolkit commands

### ISSUE THREAD

**Issue by ankur3005** [delphix/dxtoolkit#196]
** Expected Behavior**
The connection should work fine but it gives error

** Actual Behavior**
Describe what actually happened.

**Steps To Reproduce the Problem**
[oracle@dtraflocorh2021 dxtoolkit2 ]$ ./dx_get_cpu -d dtraflocodel01 -debug
Dxtoolkit version 2.4.2
Loading engines from /app/dba/public/delphix/dxtoolkit-2.4.2/dxtoolkit2/dxtools.conf
connecting to: dtraflocodel01 ( IP/name : 172.21.6.175 )
GET: http://172.21.6.175:80/resources/json/delphix/session
** GET http://172.21.6.175:80/resources/json/delphix/session ==> 200 OK
API Version: 1.3
** POST http://172.21.6.175:80/resources/json/delphix/session ==> 200 OK
GET: http://172.21.6.175:80/resources/json/delphix/about
** GET http://172.21.6.175:80/resources/json/delphix/about ==> 200 OK
API Version: 1.11
** POST http://172.21.6.175:80/resources/json/delphix/session ==> 200 OK
** POST http://172.21.6.175:80/resources/json/delphix/login ==> 500 read timeout (15s)
login to 172.21.6.175 failed.
Can't connect to Dephix Engine dtraflocodel01

**Version**
Tried dxtoolkit 2.4.2
Delphix version 6.0.9.0

**Comment by ankur3005** [comment]
Hi,

I also tried with latest version of dxtoolkit 2.4.13, but no luck

[oracle@dtraflocorh2021 dxtoolkit2 ]$ ./dx_get_appliance -d dtraflocodel01 -debug 2
Dxtoolkit version 2.4.13
-Entering Engine::constructor
-Entering Engine::load_config
Loading engines from /app/dba/public/delphix/dxtoolkit-2.4.13/dxtoolkit2/dxtools.conf
 -Loading engine dtraflocodel01
 -Loading engine dtraflocodel02
 -Loading engine dtraflocodel03
 -Loading engine dtraflocodel04
 -Loading engine dtraflocodel05
 -Loading engine dtraflocodel06
 -Loading engine dtraflocodel07
 -Loading engine dtraflocodel08
 -Loading engine dtraflocodel09
 -Loading engine dtraflocodel99
-Entering Engine::dlpx_connect
 -Cookie file /tmp/cookies.oracle.dtraflocodel01
connecting to: dtraflocodel01 ( IP/name : 172.21.6.175 )
-Entering Engine::getJSONResult
GET: http://172.21.6.175:80/resources/json/delphix/session
** GET http://172.21.6.175:80/resources/json/delphix/session ==> 200 OK
prevalidate set to false. checking variable and script for password as session doesn't exist
-Entering Engine::extended_password
-Entering Engine::session
API Version: 1.3
 -{"version":{"type":"APIVersion","major":1,"minor":3,"micro":0},"type":"APISession"}
-Entering Engine::postJSONData
-{"version":{"type":"APIVersion","major":1,"minor":3,"micro":0},"type":"APISession"}
** POST http://172.21.6.175:80/resources/json/delphix/session ==> 200 OK
 -Response message: {
   "job" : null,
   "type" : "OKResult",
   "action" : null,
   "result" : {
      "client" : null,
      "version" : {
         "type" : "APIVersion",
         "major" : 1,
         "micro" : 0,
         "minor" : 3
      },
      "locale" : null,
      "type" : "APISession"
   },
   "status" : "OK"
}

-Entering Engine::getJSONResult
GET: http://172.21.6.175:80/resources/json/delphix/about
** GET http://172.21.6.175:80/resources/json/delphix/about ==> 200 OK
-Entering Engine::session
API Version: 1.11
 -{"version":{"type":"APIVersion","minor":11,"micro":9,"major":1},"type":"APISession"}
-Entering Engine::postJSONData
-{"version":{"type":"APIVersion","minor":11,"micro":9,"major":1},"type":"APISession"}
** POST http://172.21.6.175:80/resources/json/delphix/session ==> 200 OK
 -Response message: {
   "job" : null,
   "type" : "OKResult",
   "action" : null,
   "result" : {
      "locale" : null,
      "type" : "APISession",
      "version" : {
         "type" : "APIVersion",
         "micro" : 9,
         "minor" : 11,
         "major" : 1
      },
      "client" : null
   },
   "status" : "OK"
}

-Entering Engine::login
-Entering Engine::postJSONData
-{"password":"xxxxx","type":"LoginRequest","username":"delphix_admin"}
** POST http://172.21.6.175:80/resources/json/delphix/login ==> 500 read timeout (15s)
 -HTTP POST error code: 500
 -HTTP POST error message: read timeout
login to 172.21.6.175  failed.

Appliance            Status   Version  Total (GB) Used (GB)  Free (GB)  PctUsed(%) dSource# VDBs#    Total Ob
-------------------- -------- -------- ---------- ---------- ---------- ---------- -------- -------- --------
dtraflocodel01       DOWN

**Comment by marcinops** [comment]
no a dxtoolkit bug - resolved by restart of the management stack
