### ISSUE TITLE
"11.02.2022 Parent snapshot / Parent time in dx_get_db_env"

### ISSUE THREAD

**Issue by pioro** [delphix/dxtoolkit#197]
** Expected Behavior**
Parent snapshot / time column should display a parent database snapshot used for refresh or provision operation

** Actual Behavior**
Parent snapshot / time column is displaying a parent timeflow snapshot. 
For provision / refresh operation - this is matching an expected behavior but after rollback operation
it's not displaying proper snapshot data anymore

**Steps To Reproduce the Problem**
run a dx_get_db_env after refresh and rerun a it again after rollback operation on VDB
and compare a Parent snapshot times

**Version**
All

**Comment by marcinops** [comment]
A new version of dx_get_db_env command will fix a this problem. In addition a flag _-timeflowparent_ will be added to allow customer to use this command in backward compatibility mode
