### ISSUE TITLE
02/23/2022 dx_get_replication shows 'DISABLED' for ENABLE field for all profiles

### ISSUE THREAD

**Issue by tomsyth** [delphix/dxtoolkit#200]
** Expected Behavior**
I'm not sure what is expected here. There's no concept of disabling a replication profile.

** Actual Behavior**
All replication profiles return a value of 'DISABLED' for the ENABLE field in the output.

**Steps To Reproduce the Problem**
create replication profile(s), run dx_get_replication against the engine.

See previous question

**Screenshots**
Appliance  Profile name         Replication target   Enable    Last Run             Status          Schedule                                 Run Time   Next run             Objects
---------- -------------------- -------------------- --------- -------------------- --------------- ---------------------------------------- ---------- -------------------- --------------------
de         repspec1             10.0.1.15            DISABLED  2022-02-23 14:07:34  COMPLETED       on 00 min on 00 h daily                  00:01:07   2022-02-24 00:00:00  winsrc1,orasrc1
de         repspec2             10.0.1.15            DISABLED  2022-02-23 16:00:00  COMPLETED       on 00 min every 1 h daily                00:01:00   2022-02-23 17:00:00  winsrc1

**Version**
Delphix Virtual engine 6.0.11.0
Dxtoolkit 2.4.14.1

**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by marcinops** [comment]
fixed in 2.4.15.1
