### ISSUE TITLE
"[05-23-2022] [Error while provisioning VDB through dxtoolkit command]"

### ISSUE THREAD

**Issue by shashidhara-bv** [delphix/dxtoolkit#207]
** Expected Behavior**
VDB has to be provisioned on execution of "dx_provision_vdb" with required parameters

** Actual Behavior**
When I am trying to execute "dx_provision_vdb" command with required parameters, on execution getting bellow error
"Cause: Validation of user environment failed."

**Steps To Reproduce the Problem**
Execute dxtoolkit command "dx_provision_vdb" by passing parameters like 
./dx_provision_vdb -d engine , -group , -sourcename,  -targetname,  -dbname,  -environment,  -type, -envinst 

**Screenshots**
Attached step by step screenshots
![image 1](https://user-images.githubusercontent.com/106030050/169731829-2ed45d57-b651-44b3-b888-4773868f451c.png)
![image 2](https://user-images.githubusercontent.com/106030050/169731863-54ebdb38-4b2f-4049-98bc-136a1bef2ab2.png)
![image 3](https://user-images.githubusercontent.com/106030050/169731878-d5f1396a-7358-4946-b835-c6b07dc1d35f.png)

**Version**
Continuous Data 6.0.13.1

**Additional Context**
When I browse for the solution, find suggestion like, issue is due to 'user privilege' but for the same host I have provisioned VDB through UI by logging with same user. 
Please find attached CLI exec screenshots for more details and suggest us the solution.

**Comment by pioro** [comment]
Hello,

I can't see a mount point being specified here - what mount point are you using in GUI ? 
If you don't specify a "-mntpoint" parameter a default /mnt/provision is used and this can cause problems.

Also could you please run the followng steps:

go to your home directory:
cd /home/<username>

run dxtoolkit with a full list of parameters and -debug 3
/opt/oracle/admin/dxtoolkit/install/dxtoolkit2/dx_provision_db -d xxxxxxxxxx -debug 3

This should create a debux_xxxx directory in your home folder where xxxx will be an engine name.
Could you please zip this folder and send to me ?


regards,
Marcin

**Comment by shashidhara-bv** [comment]
HI Marcin,

We are using "/mnt/nfs" as "Mount Base" in GUI while provisioning VDB, attached screenshot below.

[cid:725a1b8e-4645-41c4-9267-9a3d6cf8172d]

As per the suggestion included mountpoint parameter "-mntpoint /mnt/nfs" which I used in GUI from home directory but no luck.

Tried with below options from home directory, please verify the screenshot
1 --debug 3
2 -debug 3
3 without "-envUser oracle"
4 without "-envUser oracle" and with mountpoint parameter "-mntpoint /mnt/nfs"  -debug 3
5 with mountpoint parameter "-mntpoint /mnt/nfs" --debug 3

[cid:bfb5ea77-ad51-4e3c-aef9-c4c84248c0a1]

Regards,
Shashidhar.
________________________________
From: Marcin Przepiorowski ***@***.***>
Sent: Thursday, May 26, 2022 5:22 PM
To: delphix/dxtoolkit ***@***.***>
Cc: Shashidhara Vasanthkumar (OSV) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [delphix/dxtoolkit] "[05-23-2022] [Error while provisioning VDB through dxtoolkit command]" (Issue #207)

Caution! This email originated outside of FedEx. Please do not open attachments or click links from an unknown or suspicious origin.


Hello,

I can't see a mount point being specified here - what mount point are you using in GUI ?
If you don't specify a "-mntpoint" parameter a default /mnt/provision is used and this can cause problems.

Also could you please run the followng steps:

go to your home directory:
cd /home/

run dxtoolkit with a full list of parameters and -debug 3
/opt/oracle/admin/dxtoolkit/install/dxtoolkit2/dx_provision_db -d xxxxxxxxxx -debug 3

This should create a debux_xxxx directory in your home folder where xxxx will be an engine name.
Could you please zip this folder and send to me ?

regards,
Marcin

**Comment by pioro** [comment]
Hi,

I am sorry I mean to cd $HOME not cd /home.  
You don't have a permissions to write to /home directory - Could you please change directory to the one where you can write into and run a script ? 

Parameter -debug 3 requires to start dxtoolkit command from the directory where you have an write access, otherwise you will hit a problem which is related to lack of the write permission and this will happen before validation of your parameters.

If you want to give it a try - add -mntpoint /mnt/nfs without -debug 3 and test if this is working.

regards,
Marcin

**Comment by shashidhara-bv** [comment]
HI Marcin,

I was occupied with other activity and not able to try your instructions in last 2 days.

From cd $HOME am able to execute 'dx_provision_vdb' command with below parameter and VDB's (MOTESVDB3, MOTESVDB4, MOTESVDB5 and MOTESVDB6) has been provisioned
with and without -debug 3 but status is 'killed' instead of 'Completed'.

As an example, below command executed to provision MOTESVDB5 with -debug 3 which has provisioned but with status 'killed'.
As instructed, extracted directory "debug_uapa0008" and attached zipped folder for your analysis.
/opt/oracle/admin/dxtoolkit/install/dxtoolkit2/dx_provision_vdb -d uapa0008 -group 'Test VDB' -sourcename GMNIATS1 -targetname MOTESVDB5 -dbname MOTESDB5 -environment ACCS-SA-TGT-UDBA0140 -type oracle -envinst '/opt/oracle/product/19.0.0' -envUser oracle -mntpoint '/mnt/nfs' - debug 3

Below command executed with out -debug 3 which ended with status "killed" and when I checked in GUI VDB created with status "VDB Stopped" (please verify below screen shot for CLI and GUI)
/opt/oracle/admin/dxtoolkit/install/dxtoolkit2/dx_provision_vdb -d uapa0008 -group 'Test VDB' -sourcename GMNIATS1 -targetname MOTESVDB6 -dbname MOTESDB6 -environment ACCS-SA-TGT-UDBA0140 -type oracle -envinst '/opt/oracle/product/19.0.0' -envUser oracle -mntpoint '/mnt/nfs'

[cid:2c94b556-9e49-470b-8b61-d6c423c13fd6]



[cid:fb5a886b-b5a8-4fb6-b7ed-f2d7e820281f]



Copied attached "debug_uapa0008" directory for your verification. Please verify and suggest us to create VDB without any issue.
[cid:eded90bd-4666-4d96-bfbf-900284f09dc3]

Regards,
Shashidhar.
________________________________
From: Marcin Przepiorowski ***@***.***>
Sent: Monday, May 30, 2022 1:54 PM
To: delphix/dxtoolkit ***@***.***>
Cc: Shashidhara Vasanthkumar (OSV) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [delphix/dxtoolkit] "[05-23-2022] [Error while provisioning VDB through dxtoolkit command]" (Issue #207)

Caution! This email originated outside of FedEx. Please do not open attachments or click links from an unknown or suspicious origin.


Hi,

I am sorry I mean to cd $HOME not cd /home.
You don't have a permissions to write to /home directory - Could you please change directory to the one where you can write into and run a script ?

Parameter -debug 3 requires to start dxtoolkit command from the directory where you have an write access, otherwise you will hit a problem which is related to lack of the write permission and this will happen before validation of your parameters.

If you want to give it a try - add -mntpoint /mnt/nfs without -debug 3 and test if this is working.

regards,
Marcin

**Comment by shashidhara-bv** [comment]
HI Aaron/Marcin,

Gentle remainder, Please suggest the solution for below issue and let us know if there is need of screen sharing session.

Regards,
Shashidhar.
________________________________
