### ISSUE TITLE
"16-Jun-22 dx_get_db_env fails with - Can't call method "getName" "

### ISSUE THREAD

**Issue by pmjwh** [delphix/dxtoolkit#208]
** Expected Behavior**
output should be generated with helpful error or warning.

** Actual Behavior**
./dx_get_db_env fails with:

`Can't call method "getName" on an undefined value at script/dx_get_db_env.pl line 354.
`
**Steps To Reproduce the Problem**
if the user account accessing the engine only has **_reader_** access for the group containing the VDB and not the group containing the Parent object, this unhelpful error is thrown.

1: on engine give reader access to a group containing a VDB (parent object must be in a different group with no access granted)
2: use reader account to run the query
dx_get_db_env -d <engine>

**Screenshots**

**Version**
2.4.15.1 

**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by marcinops** [comment]
fixed in 2.4.17
