### ISSUE TITLE
"July 6th 2022 : dx_get_db_env -backup output for dsources doesnt include hooks"

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/dxtoolkit#209]
** Expected Behavior**
Running dx_get_db_env -backup  creates dxtoolkit commands for a dsources including its own hooks

** Actual Behavior**
Running dx_get_db_env -backup  creates dxtoolkit commands for a dsources but it doesn't include  its own hooks.

**Steps To Reproduce the Problem**
for instance running --> ./dx_get_db_env -d dxcarlosnw.dcol2.delphix.com -backup .

 # ./dx_get_db_env -d dxcarlosnw.dcol2.delphix.com -backup .
Exporting database DBOMSRCD94D3 hooks into  ./DBOMSRCD94D3.dbhooks
Exporting database VDBCO1 hooks into  ./VDBCO1.dbhooks

#  cat ./backup_metadata_dsource.txt
dx_ctl_dsource -d dxcarlosnw.dcol2.delphix.com -action create -group "Oracle dSources" -creategroup -dsourcename "DBOMSRCD94D3"  -type oracle -sourcename "DBOMSRCD94D3" -sourceinst "/u01/app/oracle/product/19.11.0.0/dbhome_1" -sourceenv "carorasrc" -source_os_user "oracle"  -logsync yes -logsyncmode redo
"
#  cat ./backup_metadata_vdb.txt
dx_provision_vdb -d dxcarlosnw.dcol2.delphix.com -type oracle -group "Oracle dSources" -creategroup -sourcename "DBOMSRCD94D3"  -srcgroup "Oracle dSources" -targetname "VDBCO1"  -dbname "VDBCO1" -environment "caroratgt"  -envinst "/u01/app/oracle/product/19.11.0.0/dbhome_1"  -envUser "oracle"  -hooks ./VDBCO1.dbhooks  -redoGroup 3 -redoSize 1024 -archivelog=yes -mntpoint "/mnt/provision" -instname VDBCO1 -uniqname VDBCO1

#

**Version**
Tested with dxtoolkit 2.4.16.1 and delphix engine version 6.0.13

**Comment by marcinops** [comment]
Fixed in 2.4.18
