### ISSUE TITLE
can't create JS bookmarks using time. 

### ISSUE THREAD

**Issue by dbarkin** [delphix/dxtoolkit#21]
can't create JS bookmarks using time.  If I use latest keyword, it works ok,

./dx_ctl_js_bookmarks -d engine -bookmark_name "v1.33" -bookmark_time '2017-06-13 11:50:00'  -contai
ner_name SUPPORT_A01 -action create -template_name PROD_SUPPORT_TEAM_A
Problem with job HASH(0x5216448)
Job for bookmark is not created. 

./dx_ctl_js_bookmarks -d engine -bookmark_name "v1.32" -bookmark_time latest  -container_name SUPPOR
T_A01 -action create -template_name PROD_SUPPORT_TEAM_A
Starting job JOB-1630 for bookmark v1.32.
5 - 29 - 47 - 87 - 100
Job JOB-1630 finished with state: COMPLETED

**Comment by pioro** [comment]
Hello,

Could you please run a failing command with -debug 3 ?
Than find a debug or debug_XXX directory where XXX is a Delphix Engine name 
zip it and send to me ? 

regards,
Marcin

**Comment by pioro** [comment]
it should be fixed in 2.3.3-rc1 - binaries will be uploaded soon.
Could you please check it and let me know ?

regards,
Marcin
