### ISSUE TITLE
July 26th 2022: dx_get_replication prints out additional information

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/dxtoolkit#210]
** Expected Behavior**
dx_get_replication  should print out the list of replication profiles a delphix engines has.

** Actual Behavior**
dx_get_replication  is printing out additional internal details that need to be removed as shown here:

#  ./dx_get_replication -d engine1
$VAR1 = {
          'useSystemSocksSetting' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
          'targetPort' => 8415,
          'targetPrincipal' => 'admin',
          'schedule' => '0 0 0 * * ?',
          'targetCredential' => {
                                  'password' => '********',
                                  'type' => 'PasswordCredential'
                                },
          'description' => '',
          'objectSpecification' => {
                                     'type' => 'ReplicationList',
                                     'reference' => undef,
                                     'objects' => [
                                                    'DOMAIN'
                                                  ],
                                     'namespace' => undef,
                                     'name' => undef
                                   },
          'reference' => 'REPLICATION_SPEC-1',
          'type' => 'ReplicationSpec',
          'bandwidthLimit' => 0,
          'numberOfConnections' => 1,
          'tag' => '340b12aa-8d7e-4c43-b860-34e3f95b49dd',
          'namespace' => undef,
          'encrypted' => $VAR1->{'useSystemSocksSetting'},
          'targetHost' => 'test',
          'runtime' => {
                         'type' => 'ReplicationSpecRuntime',
                         'nextScheduledExecution' => undef
                       },
          'automaticReplication' => $VAR1->{'useSystemSocksSetting'},
          'lockedProfile' => $VAR1->{'useSystemSocksSetting'},
          'name' => 'profile1'
        };
$VAR1 = {
          'schedule' => '0 0 0 * * ?',
          'targetCredential' => {
                                  'password' => '********',
                                  'type' => 'PasswordCredential'
                                },
          'description' => '',
          'targetPort' => 8415,
          'targetPrincipal' => 'admin',
          'useSystemSocksSetting' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
          'type' => 'ReplicationSpec',
          'reference' => 'REPLICATION_SPEC-2',
          'bandwidthLimit' => 0,
          'objectSpecification' => {
                                     'objects' => [
                                                    'GROUP-2'
                                                  ],
                                     'namespace' => undef,
                                     'name' => undef,
                                     'reference' => undef,
                                     'type' => 'ReplicationList'
                                   },
          'encrypted' => $VAR1->{'useSystemSocksSetting'},
          'namespace' => undef,
          'targetHost' => 'test',
          'tag' => 'd5e9e4b2-a899-408f-8ab2-296338077350',
          'numberOfConnections' => 1,
          'name' => 'profile2',
          'lockedProfile' => $VAR1->{'useSystemSocksSetting'},
          'automaticReplication' => $VAR1->{'useSystemSocksSetting'},
          'runtime' => {
                         'type' => 'ReplicationSpecRuntime',
                         'nextScheduledExecution' => undef
                       }
        };

Appliance  Profile name         Replication target   Enable    Last Run             Status          Schedule                                 Run Time   Next run             Objects
---------- -------------------- -------------------- --------- -------------------- --------------- ---------------------------------------- ---------- -------------------- --------------------
engine1    profile1             test                 DISABLED  N/A                  N/A             on 00 min on 00 h daily                  N/A        N/A                  DOMAIN
engine1    profile2             test                 DISABLED  N/A                  N/A             on 00 min on 00 h daily                  N/A        N/A                  dSources

**Steps To Reproduce the Problem**
1.-   Run  dx_get_replication -d engine1 against a configured engine.

**Version**
This was tested in 2.4.16.1:
 ./dx_get_replication -d engine1
Dxtoolkit version 2.4.16.1

**Comment by marcinops** [comment]
fixed in 2.4.16.3
