### ISSUE TITLE
"September 16th 2022: dx_get_db_env stopping after database api and not creating export files"

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/dxtoolkit#216]
** Expected Behavior**
dx_get_db_env is not creating export files with metadata to recreate dsources

** Actual Behavior**
At customer, we tested in 2 engines with similar type of dsources(MSSQL) and same delphix version (6.0.15) and noticed that for one it is failing to create the export files.

This engine is working successfully and export files are created:

$ /dxtoolkit2/dx_get_db_env  -d engine4 -backup /backup -name MSSQL4 -type dsource --debug 3 > log.log

Dxtoolkit version 2.4.16.1

Loading engines from /dxtoolkit2/dxtools.conf

connecting to: engine4 ( IP/name : 1.1.1.1 )

** GET [http://1.1.1.1:80/resources/json/delphix/session](http://1.1.1.1/resources/json/delphix/session) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/user/current](http://1.1.1.1/resources/json/delphix/user/current) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/source](http://1.1.1.1/resources/json/delphix/source) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/sourceconfig](http://1.1.1.1/resources/json/delphix/sourceconfig) ==> 200 OK (2s)

** GET [http://1.1.1.1:80/resources/json/delphix/repository](http://1.1.1.1/resources/json/delphix/repository) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/environment](http://1.1.1.1/resources/json/delphix/environment) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/environment/oracle/clusternode](http://1.1.1.1/resources/json/delphix/environment/oracle/clusternode) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/environment/windows/clusternode](http://1.1.1.1/resources/json/delphix/environment/windows/clusternode) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/environment/user](http://1.1.1.1/resources/json/delphix/environment/user) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/environment/oracle/listener](http://1.1.1.1/resources/json/delphix/environment/oracle/listener) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/host](http://1.1.1.1/resources/json/delphix/host) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/namespace](http://1.1.1.1/resources/json/delphix/namespace) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/toolkit](http://1.1.1.1/resources/json/delphix/toolkit) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/database](http://1.1.1.1/resources/json/delphix/database) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/namespace](http://1.1.1.1/resources/json/delphix/namespace) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/group](http://1.1.1.1/resources/json/delphix/group) ==> 200 OK

** GET [http://1.1.1.1:80/resources/json/delphix/database/template](http://1.1.1.1/resources/json/delphix/database/template) ==> 200 OK

For this one it is not working fine, it is not creating the export files and  you can see that its stopping on the database API:

$ /dxtoolkit2/dx_get_db_env  -d engine5 -backup /backup -name MSSQL5 -type dsource --debug 3 > log.log

Dxtoolkit version 2.4.16.1

Loading engines from /dxtoolkit2/dxtools.conf

connecting to: engine5 ( IP/name : 2.2.2.2 )

GET: [http://2.2.2.2:80/resources/json/delphix/session](http://2.2.2.2/resources/json/delphix/session)

** GET [http://2.2.2.2:80/resources/json/delphix/session](http://2.2.2.2/resources/json/delphix/session) ==> 200 OK

Session exists.

GET: [http://2.2.2.2:80/resources/json/delphix/user/current](http://2.2.2.2/resources/json/delphix/user/current)

** GET [http://2.2.2.2:80/resources/json/delphix/user/current](http://2.2.2.2/resources/json/delphix/user/current) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/source](http://2.2.2.2/resources/json/delphix/source)

** GET [http://2.2.2.2:80/resources/json/delphix/source](http://2.2.2.2/resources/json/delphix/source) ==> 200 OK (1s)

GET: [http://2.2.2.2:80/resources/json/delphix/sourceconfig](http://2.2.2.2/resources/json/delphix/sourceconfig)

** GET [http://2.2.2.2:80/resources/json/delphix/sourceconfig](http://2.2.2.2/resources/json/delphix/sourceconfig) ==> cd200 OK (3s)

GET: [http://2.2.2.2:80/resources/json/delphix/repository](http://2.2.2.2/resources/json/delphix/repository)

** GET [http://2.2.2.2:80/resources/json/delphix/repository](http://2.2.2.2/resources/json/delphix/repository) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/environment](http://2.2.2.2/resources/json/delphix/environment)

** GET [http://2.2.2.2:80/resources/json/delphix/environment](http://2.2.2.2/resources/json/delphix/environment) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/environment/oracle/clusternode](http://2.2.2.2/resources/json/delphix/environment/oracle/clusternode)

** GET [http://2.2.2.2:80/resources/json/delphix/environment/oracle/clusternode](http://2.2.2.2/resources/json/delphix/environment/oracle/clusternode) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/environment/windows/clusternode](http://2.2.2.2/resources/json/delphix/environment/windows/clusternode)

** GET [http://2.2.2.2:80/resources/json/delphix/environment/windows/clusternode](http://2.2.2.2/resources/json/delphix/environment/windows/clusternode) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/environment/user](http://2.2.2.2/resources/json/delphix/environment/user)

** GET [http://2.2.2.2:80/resources/json/delphix/environment/user](http://2.2.2.2/resources/json/delphix/environment/user) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/environment/oracle/listener](http://2.2.2.2/resources/json/delphix/environment/oracle/listener)

** GET [http://2.2.2.2:80/resources/json/delphix/environment/oracle/listener](http://2.2.2.2/resources/json/delphix/environment/oracle/listener) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/host](http://2.2.2.2/resources/json/delphix/host)

** GET [http://2.2.2.2:80/resources/json/delphix/host](http://2.2.2.2/resources/json/delphix/host) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/namespace](http://2.2.2.2/resources/json/delphix/namespace)

** GET [http://2.2.2.2:80/resources/json/delphix/namespace](http://2.2.2.2/resources/json/delphix/namespace) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/toolkit](http://2.2.2.2/resources/json/delphix/toolkit)

** GET [http://2.2.2.2:80/resources/json/delphix/toolkit](http://2.2.2.2/resources/json/delphix/toolkit) ==> 200 OK

GET: [http://2.2.2.2:80/resources/json/delphix/database](http://2.2.2.2/resources/json/delphix/database)

** GET [http://2.2.2.2:80/resources/json/delphix/database](http://2.2.2.2/resources/json/delphix/database) ==> 200 OK

Gateway

Can't use an undefined value as an ARRAY reference at /tmp/par-73762d64656c706869782d61646d696e/cache-7270036ce8539cb248e10ca69a42c3a13e5e4da0/inc/lib/Databases.pm line 113.

Can you please help us review this?

**Version**
Delphix engine 6.0.15
dxtoolkit 2.4.16.1

**Comment by marcinops** [comment]
workaround applied in 2.4.17 
Better mechanism to detect an engine reboot and states is required
