### ISSUE TITLE
dx_v2p fails when provided with dataDirectory parameter

### ISSUE THREAD

**Issue by mwatson-delphix** [delphix/dxtoolkit#218]
** Expected Behavior**
dx_v2p ( oracle ) should accept 

 [ -archiveDirectory arch_directory ]
          [ -dataDirectory data_dir ]
          [ -externalDirectory external_dir ]
          [ -tempDirectory temp_dir ]

Problem with export file system layout. Is targetDiretory and dataDirectory set ?

** Actual Behavior**

Supplying any of these parameters results in a failure.

`Problem with export file system layout. Is targetDiretory and dataDirectory set ?`

**Steps To Reproduce the Problem**

Perform an Oracle V2P, using any of the following parameters,

 [ -archiveDirectory arch_directory ]
          [ -dataDirectory data_dir ]
          [ -externalDirectory external_dir ]
          [ -tempDirectory temp_dir ]

**Screenshots**

**Version**
Latest from source, e2d07759b0600d9b572572f1fe6dba3d900f1d3d

**Additional Context**

I believe this is due to .OracleVDB_obj.setFileSystemLayout not explicitly returning "0" on successful exit, resulting in the last variable assignment being returned instead.

**Comment by marcinops** [comment]
fixed in 2.4.17
