### ISSUE TITLE
"Nov-03-2022 dx_v2p with sql server reports that targetDirectory is required, but it's an optional parameter"

### ISSUE THREAD

**Issue by tomsyth** [delphix/dxtoolkit#219]
** Expected Behavior**
https://docs.delphix.com/docs/datasets/getting-started/provisioning-and-managing-virtual-databases/virtual-to-physical/customizing-target-directory-structure-for-database-export#CustomizingTargetDirectoryStructureforDatabaseExport-Targetdirectoryisempty

If target directory is empty, then destinations don't share a common root path.

** Actual Behavior**
Cannot run command without specifying targetDirectory.

**Steps To Reproduce the Problem**
Run dx_v2p for sql server without specifying targetDirectory parameter.

**Version**
2.4.17

**Comment by marcinops** [comment]
Will be fixed in 2.4.17.2
