### ISSUE TITLE
"December 22nd 2022: To add the capability to show vdb/dsource sizes in different metrics - MB, GB, TB among others"

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/dxtoolkit#220]
**Is your feature request related to a problem? Please describe.**
Customers would like to have the option when printing vdb/dsource sizes of what metric they want to use - MB, GB, TB among others

**Describe the solution you'd like**
If possible to add a new parameters to specify which metric we would like to use - for instance on dx_get_vdbsize to add something like -gb or -mb to print sizes on that metric.
However, this would be good to have across all dxtoolkit commands that print out sizes.

**Comment by marcinops** [comment]
Will be fixed in 2.4.18
