### ISSUE TITLE
"Jan 10th, 2023 vPDB lenght name should not be limited to 8 characters"

### ISSUE THREAD

**Issue by jose-prieto-dlpx** [delphix/dxtoolkit#221]
** Expected Behavior**
When provisioning a new vPDB we provide the vPDB name in the -dbname parameter and this should be created even if the name is longer that 8 characters as the actual limit is 30.

** Actual Behavior**
The provision of a new vPDB with a name longer that 8 characters fails with
`Max. size of dbname for Oracle is 8 characters
.VDB won't be created`
 

**Steps To Reproduce the Problem**
`dx_provision_vdb.exe -d http://myengine.delphix.com -type oracle -group "Test_Group" -creategroup -sourcename "TESTSRC_PDB"  -srcgroup "Test_src_group" -targetname "TESTTGT_PDB"  -dbname "TESTTGT_PDB" -environment "Test_Env"  -envinst "/opt/oracle/product/db/19.16"  -envUser "delphix_os"  -hooks C:\temp2\Delphix\dxtoolkit\TESTTGT_PDB.dbhooks -maskedbyscript  -vcdbinstname TESTTGT -vcdbname TESTTGT -vcdbdbname TESTTGT -vcdbuniqname TESTTGT -vcdbgroup "Test_group" -mntpoint "/Delphix"`

**Version**
2.4.17

**Comment by marcinops** [comment]
Will be fixed in 2.4.18
