### ISSUE TITLE
"Jan 10th,  Incorrect maskedbyscript flag in backup command"

### ISSUE THREAD

**Issue by jose-prieto-dlpx** [delphix/dxtoolkit#222]
** Expected Behavior**
The DXToolkit command generated with the  dx_get_db_env should work out of the box even our of VDBs with masked parents.

** Actual Behavior**
A command generated with  dx_get_db_env includes the flag -maskedbyscript when the parent of a VDB is masked. This leads to an error message:
> Error: Cannot provision a masked VDB from a VDB whose data has already been masked.

**Steps To Reproduce the Problem**

1. Provision a VDB from a masked VDB.
2. Obtain the dxtoolkit command to re-create the new VDB using dx_get_db_env with the -backup flag
3. Attempt to execute the generated command

**Version**
2.4.17

**Comment by marcinops** [comment]
Will be fixed in 2.4.18
