### ISSUE TITLE
"27.02.2023 Link functionality affected for dSources if moved between Data Guard primary / standby database"

### ISSUE THREAD

**Issue by pioro** [delphix/dxtoolkit#226]
** Expected Behavior**
One should be link dSource after switchover of roles

** Actual Behavior**
Wrong configuration is selected 

**Steps To Reproduce the Problem**
Unlink dSource ( CDB and PDB)
switchover roles of database
Link dSource ( CDB and PDB) - it may work for first switch
Unlink dSource ( CDB and PDB)
switchover roles of database
Link CDB
Link PDB - it's failing

**Version**
all version affected

**Comment by pioro** [comment]
Workaround:

Provide both parameters:
-sourceenv
-sourceinst

Oracle PDB allows multiple entry with same name

**Comment by marcinops** [comment]
Fixed in 2.4.19
