### ISSUE TITLE
"April 26, 2023 gunzip/untar of release 2.4.19.2-redhat7 create directory bin and dxtoolkit2"

### ISSUE THREAD

**Issue by Ranzo3** [delphix/dxtoolkit#230]
** Expected Behavior**
dxToolkit files should all be in their own directory.  Creating "bin" directory at same level as dxtoolkit2 might not be desired
** Actual Behavior**
when tar -xvf the release, creates dxtoolkit2 and bin directories

**Additional Context**
It's a small issue, and maybe it's desirable and can be closed as Won't Fix.  Personally I'd prefer to have everything in dxtoolkit2 and these examples in a subfolder of dxtoolkit2

**Comment by marcinops** [comment]
fixed in 2.4.22
