### ISSUE TITLE
"2021-05-04: dx_snapshot_db support for staging push dSources"

### ISSUE THREAD

**Issue by nstack21** [delphix/dxtoolkit#232]
**Is your feature request related to a problem? Please describe.**
Staging push is a new Delphix feature with some new APIs. Customer's would like to use dx_snapshot_db in a script to make their dSource take a snapshot (after restoring a backup to the database). For a SQL Server staging push dSource, I see that it is using the following parameters when I click the camera icon:

> 172.16.124.50 - - [01/May/2023:10:28:34 -0600] "POST /resources/json/delphix/database/MSSQL_DB_CONTAINER-136/sync HTTP/1.1" 200 85 117 {"type":"MSSqlNoBackupSyncParameters"}

**Describe the solution you'd like**
It would be great if dx_snapshot_db had a new parameter to run a snapshot on a staging push dSource.

**Describe alternatives you've considered**
I was able to use the CLI:
> % echo "/database; select McLaren_Staging; sync; set type=MSSqlNoBackupSyncParameters; commit" | ssh [admin@neal6017.dcol2.delphix.com](mailto:admin@neal6017.dcol2.delphix.com)

**Additional context**
There may be different parameters for the different staging push data platforms supported by Delphix:

- https://documentation.delphix.com/continuous-data-9-0-0-0/docs/en/oracle-staging-push-overview
- https://documentation.delphix.com/continuous-data-9-0-0-0/docs/en/staging-push-implementation-for-sql-server
- https://documentation.delphix.com/continuous-data-9-0-0-0/docs/en/staging-push-implementation-details

**Comment by marcinops** [comment]
fixed in 2.4.21
