### ISSUE TITLE
dxtoolkit2 installation and usage on windows machine

### ISSUE THREAD

**Issue by GSPKumar** [delphix/dxtoolkit#233]
Hi All,

We have recently build delphix engine version 12.0.0.0, However, i would like to use dxtoolkit2, unfortunatly i am unable to install it. could someone please help me to install and usage of dxtoolkit.

Best regards,
siva

**Comment by marcinops** [comment]
Hi,

You need to download a binary release from this link - https://github.com/delphix/dxtoolkit/releases/tag/v2.4.19.2
for your operating system and then uncompressed it and run install.sh or install.cmd
