### ISSUE TITLE
"10 Aug 2023 [Update users not working]"

### ISSUE THREAD

**Issue by itskvad** [delphix/dxtoolkit#234]
** Expected Behavior**
Describe what should have happened.

Update LDAP users principal username

** Actual Behavior**
Describe what actually happened.

No change

**Steps To Reproduce the Problem**
Describe in as much detail as possible how to reproduce the problem.

1. Update user principal in csv 
2. Run dx_ctl_users -d SERVERNAME -file update-users.csv
3. Command output is the following:

User x1 updated.
User x2 updated.

4. User principals not updated.

**Screenshots**

**Version**
Indicate the relevant versions of components. This may include the package version, operating system version, or other components relevant to the project.

v2.4.20
RHEL8.x

**Additional Context**
Add any other context about the problem here, including additional logs or debugging information if appropriate.

**Comment by marcinops** [comment]
fixed in 2.4.22 - be out soon
