### ISSUE TITLE
12-01-2023 Add support for Amazon Linux 2023

### ISSUE THREAD

**Issue by ajaytho** [delphix/dxtoolkit#236]
dxtoolkit is currently supported on rhel 6/7/8 and Ubuntu. Amazon Linux 2023 is not among the supported list

Tried rhel 6/7/8 and Ubuntu version on Amazon Linux 2023 but it fails to load shared libraries e.g.
Redhat 8
`/dx_get_appliance --help
./dx_get_appliance: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`

Ubuntu
`./dx_get_appliance --help
/tmp/par-6563322d75736572/cache-7cecac922bea02894b65f9c25ae70b472068bf57/dx_get_appliance: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`

**Comment by marcinops** [comment]
fixed in 2.4.22 - released soon
