### ISSUE TITLE
"2023-12-13 dx_ctl_users supports api_user but not documented in csv example, executable help, or wiki"

### ISSUE THREAD

**Issue by Ranzo3** [delphix/dxtoolkit#237]
Small bug to add the support for api_user in the dxusers.csv example, the help text for the executable, and the wiki page.

**Comment by ambarishgopinath** [comment]
I will check on this

**Comment by marcinops** [comment]
fixed in 2.4.23 by https://github.com/delphix/dxtoolkit/pull/239
