### ISSUE TITLE
-help should not contain .pl extension

### ISSUE THREAD

**Issue by hkpatv** [delphix/dxtoolkit#3]
Very very minor issue, but I thought I would raise it :)

dx_refresh_db -help
SYNOPSIS
     dx_refresh_db.pl [ -engine|d <delphix identifier> | -all ] < -group group_name | -name db_name | -host host_name | -type dsource|vdb >

**Comment by pioro** [comment]
Thank you for your comment. I will review help looking for issues like this.

regards,
Marcin

**Comment by pioro** [comment]
Fixed in 2.3.0-rc1 commit https://github.com/delphix/dxtoolkit/commit/e39ff9c98fa1a6afe63e52bfeea4dc89b455aca5
