### ISSUE TITLE
dx_provision_vdb.pl $self->(_source)->getSourceConfigType() returning null

### ISSUE THREAD

**Issue by largbae** [delphix/dxtoolkit#30]
Hello!

We are trying to provision an Oracle Single Instance target VDB from a RAC source on Delphix 5.1.4 engine. After "Entering VDB_obj::getSourceConfigType", we receive an error "Use of uninitialized value $configtype in string eq at OracleVDB_obj.pm line 1512. This later results in the OracleProvisionParameters JSON containing "sourceConfig"->"type" = null, which causes the provision to fail.

If I add a terrible little hack at line 1514 in OracleVDB_obj.pm as follows, the provision works perfectly:
if (! $configtype) {
  $configtype = "OracleRACConfig"
}

We are using the hack to move on for now. I tried using several back versions with similar results, currently using commit 3c871dbcb.

**Comment by pioro** [comment]
Hello,

This used to be know issue and it was resolved in v2.3.3.1 - did you tried this release ?
I will check a master code but it can be broken there as I'm adding a support for vCDBs

If it still doesn't work for you - could you please run this 

dx_provision_db <your settings> -debug 3

zip a debug directory created in current folder and attach to this issue ?

regards,
Marcin

**Comment by pioro** [comment]
Also are you deploying a vPDB into RAC CDB or this is single tenant configuration ? 

regards,
Marcin

**Comment by largbae** [comment]
Hey there,  sorry still working on my client's permission to send the
debugs.  The source database is RAC OneNode single tenant.  The dsource was
detached if that makes a difference.  Higher in the debug output it is
pretty clear that the dsource type is retrieved via some other call to
delphix,  but I wasn't able to track down where that data would be copied
into the source config type.

On Dec 7, 2017 6:45 AM, "Marcin Przepiorowski" <notifications@github.com>
wrote:

Also are you deploying a vPDB into RAC CDB or this is single tenant
configuration ?

regards,
Marcin

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/delphix/dxtoolkit/issues/30#issuecomment-349944262>,
or mute
the thread

**Comment by pioro** [comment]
Hi,

I found an issue with a code. It doesn't for then dSource is detatched and this is your case.
I already fixed it but didn't push code yet as I'm working on other piece of same file. It should be commited today so you can grab latest sources.

regards,
Marcin

**Comment by pioro** [comment]
Hi,

Please pull a latest commit and check if this is working for you now.

regards,
Marcin

**Comment by largbae** [comment]
This is working perfectly, both for Active and Detached. Thank you!!

-Braden Gibson
  813-699-9292
