### ISSUE TITLE
Extract data for analytics is working for some metrics but not for cpu

### ISSUE THREAD

**Issue by diegoloureda** [delphix/dxtoolkit#32]
[monitor@pidelphix4vapp dxtoolkit2]$ ./dx_get_analytics -d asappu301devv -i 60 -t cpu -outdir .
Connected to Delphix Engine asappu301devv (IP 10.109.128.164)

Gathering data for cpu
[monitor@pidelphix4vapp dxtoolkit2]$ ./dx_get_analytics -d asappu301devv -i 60 -t cpu -outdir . --debug 3
Dxtoolkit version 2.3.3.1
-Entering Engine::constructor
-Entering Engine::load_config
Loading engines from /home/monitor/dxtoolkit2/dxtools.conf
 -Loading engine dlphxoma001vapp
 -Loading engine dlphxrtp001vapp
 -Loading engine pidelphix1vapp
 -Loading engine pidelphix2vapp
 -Loading engine pidelphix3vapp
 -Loading engine pidelphix5vapp
 -Loading engine filidelph1vapp
 -Loading engine dlfxrtp001vapp
 -Loading engine vdfxoma2fpcms01
 -Loading engine vdfxoma2fpcms03
 -Loading engine asappu201devv
 -Loading engine asappu301devv
 -Loading engine asappu401devv
 -Loading engine asappu402devv
 -Loading engine asappu403devv
 -Loading engine asappu404devv
 -Loading engine asappu501devv
 -Loading engine sipddelphix1
-Entering Engine::dlpx_connect
 -Cookie file /tmp/cookies.monitor.asappu301devv
connecting to: asappu301devv ( IP/name : 10.109.128.164 )
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/delphix/session
** GET http://10.109.128.164:80/resources/json/delphix/session ==> 200 OK
-Entering Engine::getEngineName
Session exists.
-Entering Engine::getIP
Connected to Delphix Engine asappu301devv (IP 10.109.128.164)

-Entering Engine::getTime
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/service/configure/currentSystemTime
** GET http://10.109.128.164:80/resources/json/service/configure/currentSystemTime ==> 200 OK
-Entering Engine::getEngineName
-Entering Engine::getTimezone
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/service/configure/currentSystemTime
** GET http://10.109.128.164:80/resources/json/service/configure/currentSystemTime ==> 200 OK
-Entering Engine::getEngineName
-Entering Analytics::constructor
-Entering Analytic::getAnalyticsList
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/delphix/analytics
** GET http://10.109.128.164:80/resources/json/delphix/analytics ==> 200 OK (1s)
-Entering Engine::getEngineName
-Entering Analytic_cpu_obj::constructor
-Entering Analytics_obj::constructor
-Entering Engine::getTimezone
-Entering Analytic_io_obj::constructor
-Entering Analytics_obj::constructor
-Entering Engine::getTimezone
-Entering Analytic_io_obj::constructor
-Entering Analytics_obj::constructor
-Entering Engine::getTimezone
-Entering Analytic_network_obj::constructor
-Entering Analytics_obj::constructor
-Entering Engine::getTimezone
-Entering Analytic_io_obj::constructor
-Entering Analytics_obj::constructor
-Entering Engine::getTimezone
-Entering Analytic_tcp_obj::constructor
-Entering Analytics_obj::constructor
-Entering Engine::getTimezone
-Entering Environment_obj::constructor
-Entering Environment_obj::getEnvironmentList
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/delphix/environment
** GET http://10.109.128.164:80/resources/json/delphix/environment ==> 200 OK
-Entering Engine::getEngineName
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/delphix/environment/oracle/clusternode
** GET http://10.109.128.164:80/resources/json/delphix/environment/oracle/clusternode ==> 200 OK
-Entering Engine::getEngineName
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/delphix/environment/windows/clusternode
** GET http://10.109.128.164:80/resources/json/delphix/environment/windows/clusternode ==> 200 OK
-Entering Engine::getEngineName
-Entering Environment_obj::listEnvironmentUsers
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/delphix/environment/user
** GET http://10.109.128.164:80/resources/json/delphix/environment/user ==> 200 OK (3s)
-Entering Engine::getEngineName
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getPrimaryUser
-Entering Environment_obj::getEnvironmentListeners
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/delphix/environment/oracle/listener
** GET http://10.109.128.164:80/resources/json/delphix/environment/oracle/listener ==> 200 OK
-Entering Engine::getEngineName
-Entering Analytics::get_perf
-Entering Analytics::getAnalyticByName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getAnalytics
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getAnalyticByName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getAnalytics
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Analytics::getName
-Entering Analytics_obj::getName
-Entering Engine::getEngineName
-Entering Analytics_obj::getName
Gathering data for cpu
-Entering Analytic_cpu_obj::getData
-Entering Engine::getJSONResult
GET: http://10.109.128.164:80/resources/json/delphix/analytics/ANALYTICS_STATISTIC_SLICE-4/getData?&resolution=60&startTime=2017-12-13T16%3A14%3A51.000Z
** GET http://10.109.128.164:80/resources/json/delphix/analytics/ANALYTICS_STATISTIC_SLICE-4/getData?&resolution=60&startTime=2017-12-13T16%3A14%3A51.000Z ==> 500 read timeout (60s)
 -HTTP GET error code: 500
 -HTTP GET error message: read timeout
Response message: $VAR1 = undef;
$VAR2 = 2;

-Entering Analytics_obj::getName
Error gathering a data for cpu
[monitor@pidelphix4vapp dxtoolkit2]$

**Comment by pioro** [comment]
timeout issue - should be resolved by changing timeout in config file
