### ISSUE TITLE
dx_ctl_js_template not allowing 2 datasource of same type.

### ISSUE THREAD

**Issue by delphixgithub** [delphix/dxtoolkit#33]
I am trying to create a template with 2 mssql database but it is throwing me the below error:

./dx_ctl_js_template -d Lab -source "SOURCE,DB1,mssql,1" -source "SOURCE,DB2,mssql,1" -action create -template_name dx_demo_new
Error: The operation could not be completed because a JS_DATA_SOURCE with the following fields already exists: data layout (JS_DATA_TEMPLATE-7), name (mssql).
Problem with creating a template dx_demo_new

**Comment by pioro** [comment]
Hello,

Source name - "mssql" - needs to be unique - this is not a dxtoolkit limitation as same requirements remains in self service GUI.

regards,
Marcin
