### ISSUE TITLE
Perl modules

### ISSUE THREAD

**Issue by smouhssine** [delphix/dxtoolkit#4]
Hi,

It can be a great idea to add to the readme the list of requited perl modules to get the toolkit working

Regrads,

Mouhssine

**Comment by pioro** [comment]
Hi Mouhssine,

List of modules for source is presented on the main dxtoolkit page in source section.
Please find it below as well

Source version

Perl version 5.16 or higher

Required packages

    JSON
    Date::Manip
    DateTime::Event::Cron::Quartz
    DateTime::Format::DateParse
    Crypt::CBC
    Crypt::Blowfish
    Text::CSV
    Try::Tiny
    LWP::UserAgent
    Net::SSLeay
    IO::Socket::SSL
    LWP::Protocol::https

regards,
Marcin
