### ISSUE TITLE
dx_get_analytics does not retrieve data for 24 hrs

### ISSUE THREAD

**Issue by rahimcetinel** [delphix/dxtoolkit#41]
You can see from below example/command that dx_get_analytics does not work between the start and end of 24 hour period

D:\dxtools\dxtoolkit>dx_get_analytics.exe -t standard -outdir d:\dxtools -i 60 **-st 2018-03-25 [00:00:00]** **-et 2018-03-25 [23:59:00]**
Connected to Delphix Engine delphix1 (IP 10.1.60.220)

**Gathering data for cpu
No data returned for analytics cpu. Consider restarting collector**

When same command is run as following (please note that the date must be changed to 25 instead of 24): 

D:\dxtools\dxtoolkit>dx_get_analytics.exe -t standard -outdir d:\dxtools -i 60 **-st 2018-03-24 [00:00:00]** **-et 2018-03-25 [00:00:00]**
Connected to Delphix Engine delphix1 (IP 10.1.60.220)

Gathering data for cpu
Generating cpu raw report file d:\dxtools/delphix1-analytics-cpu-raw.csv
Generating cpu aggregated report file d:\dxtools/delphix1-analytics-cpu-aggregated.csv
Gathering data for disk
Generating disk raw report file d:\dxtools/delphix1-analytics-disk-raw.csv
Generating disk aggregated report file d:\dxtools/delphix1-analytics-disk-aggregated.csv
Gathering data for network
Generating network raw report file d:\dxtools/delphix1-analytics-network-raw.csv

Generating network aggregated report file d:\dxtools/delphix1-analytics-network-aggregated.csv
Gathering data for nfs
Generating nfs raw report file d:\dxtools/delphix1-analytics-nfs-raw.csv
Generating nfs aggregated report file d:\dxtools/delphix1-analytics-nfs-aggregated.csv

**Comment by pioro** [comment]
Hi,

The proper syntax for -st is "YYYY-MM-DD HH24:MI:SS" or "YYYY-MM-DD".
[ bracket in documentation mean an optional part of string and if you are using it bracket should not be included in string.
Strings separated by space, should be enclosed by double quotes.

regards,
Marcin
