### ISSUE TITLE
dx_provision_db fails in Delphix Engine 5.1.3.1  

### ISSUE THREAD

**Issue by bbalior** [delphix/dxtoolkit#5]
There is new required field in DE 5.1.3.1 - AutoVDBRestart

VDB provision fails with error code:
Error: source->allowAutoVDBRestartOnHostReboot->This field is required.

**Comment by pioro** [comment]
Hello,

Thank you for your comment. Current stable version 2.2.6 is not supporting Delphix 5.1.x. I'm working on it right now and new release candidate should be available soon.

As a workaround you can try this.

1. dx_logout -d engine - to logout a current session
2. dx_provision_db -dbver 5.0 <and put rest of parameters there>


regards,
Marcin

**Comment by pioro** [comment]
Fixed in 2.3.0-rc1 commit https://github.com/delphix/dxtoolkit/commit/e39ff9c98fa1a6afe63e52bfeea4dc89b455aca5
