### ISSUE TITLE
Weirdness using "-st" filter for "dx_get_audit"?

### ISSUE THREAD

**Issue by timothyjgorman** [delphix/dxtoolkit#54]
I'm seeing faulty behavior when specifying the start-time (i.e. "-st") filter on the "dx_get_audit" command?

For example, here is output when filtering from 20-Aug to the present (24-Aug)...

`$ ./dx_get_audit -d tim5230 -st "2018-08-20T00:00:00.000Z" -format csv
#Appliance,StartTime,State,User,Type,Details
tim5230,2018-08-20 16:22:07 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-13T22:14:23.586Z".
tim5230,2018-08-21 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "seaside".
tim5230,2018-08-21 04:30:00 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "R2PDB1".
tim5230,2018-08-21 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "PDBX2".
tim5230,2018-08-21 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "PDBX1".
tim5230,2018-08-21 04:30:00 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "12102 ORACLE_HOME".
tim5230,2018-08-21 04:30:03 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "carmel".
tim5230,2018-08-21 04:30:29 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "monterey".
tim5230,2018-08-21 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-14T10:32:45.046Z".
tim5230,2018-08-21 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-21T10:33:19.711Z".
tim5230,2018-08-21 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-14T10:32:25.669Z".
tim5230,2018-08-21 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-14T03:30:55.989".
tim5230,2018-08-21 04:52:01 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-14T10:31:47.498Z".
tim5230,2018-08-22 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "seaside".
tim5230,2018-08-22 04:30:00 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "R2PDB1".
tim5230,2018-08-22 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "PDBX1".
tim5230,2018-08-22 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "PDBX2".
tim5230,2018-08-22 04:30:00 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "12102 ORACLE_HOME".
tim5230,2018-08-22 04:30:06 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "carmel".
tim5230,2018-08-22 04:30:18 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "monterey".
tim5230,2018-08-22 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-22T10:32:11.289Z".
tim5230,2018-08-22 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-15T10:33:13.040Z".
tim5230,2018-08-22 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-15T03:30:58.629".
tim5230,2018-08-22 04:52:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-15T10:32:15.660Z".
tim5230,2018-08-22 16:22:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-15T22:08:01.413Z".
tim5230,2018-08-23 04:30:00 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "12102 ORACLE_HOME".
tim5230,2018-08-23 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "PDBX1".
tim5230,2018-08-23 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "PDBX2".
tim5230,2018-08-23 04:30:00 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "R2PDB1".
tim5230,2018-08-23 04:30:03 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "carmel".
tim5230,2018-08-23 04:30:17 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "monterey".
tim5230,2018-08-23 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-16T10:30:17.094Z".
tim5230,2018-08-23 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-16T10:32:22.906Z".
tim5230,2018-08-23 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-23T10:31:40.910Z".
tim5230,2018-08-23 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-16T10:33:17.592Z".
tim5230,2018-08-23 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-16T03:30:49.889".
tim5230,2018-08-23 04:52:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-16T10:32:28.166Z".
tim5230,2018-08-24 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "PDBX2".
tim5230,2018-08-24 04:30:00 MDT,FAILED,internal,DB_SYNC,Run SnapSync for database "PDBX1".
tim5230,2018-08-24 04:30:00 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "R2PDB1".
tim5230,2018-08-24 04:30:00 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "12102 ORACLE_HOME".
tim5230,2018-08-24 04:30:03 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "carmel".
tim5230,2018-08-24 04:30:17 MDT,COMPLETED,internal,DB_SYNC,Run SnapSync for database "monterey".
tim5230,2018-08-24 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-17T10:32:44.511Z".
tim5230,2018-08-24 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-17T03:30:37.194".
tim5230,2018-08-24 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-17T10:31:43.520Z".
tim5230,2018-08-24 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-17T10:30:12.166Z".
tim5230,2018-08-24 04:37:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-24T10:31:34.159Z".
tim5230,2018-08-24 04:52:00 MDT,COMPLETED,internal,SNAPSHOT_DELETE,Delete snapshot "@2018-08-17T10:31:55.601Z".
tim5230,2018-08-24 16:38:13 MDT,COMPLETED,internal,USER_LOGIN,Log in as user "delphix_admin" from IP "172.16.124.11".`

Now, changing the "-st" filter to filter from 24-Aug (midnight) onwards...

`$ ./dx_get_audit -d tim5230 -st "2018-08-24T00:00:00.000Z" -format csv
#Appliance,StartTime,State,User,Type,Details
tim5230,2018-08-24 16:38:13 MDT,COMPLETED,internal,USER_LOGIN,Log in as user "delphix_admin" from IP "172.16.124.11".`

There is timezone math of which to be aware.  The "StartTime" field in the output data is in Mountain Daylight Time, which is "-6:00" from UTC, while the timestamp value is in UTC (i.e. "yyyy-mm-ddThh:mi:ss.fffZ").

One would expect to see the second call output the last thirteen rows output by the first call (i.e. all rows newer than 24-Aug 00:00 UTC or 23-Aug 18:00 MDT).

If you have access to Delphix DCenter, the attached "dxtools.conf" file will be helpful to reproduce the problem and the underlying data.
[dxtools.conf.txt](https://github.com/delphix/dxtoolkit/files/2320154/dxtools.conf.txt)

**Comment by pioro** [comment]
Hi Tim,

Thanks for raising this issue. -ST parameter is treating a value of this parameter as it is supplied in timezone which is used by Delphix Engine. If you want to display all events after midnight MDT - st parameter should looks like this -st " 2018-08-24 00:00:00". There is an assumption that all input and output dates are handled using a Delphix Engine timezone, and this is different if you compare it with Delphix API.

Ex:

```
./dx_get_audit -d tim5230 -st "2018-08-24T00:00:00.000Z" -debug
Dxtoolkit version 2.3.6
Loading engines from /mnt/c/Users/pioro/Documents/oss_delphix/dxtoolkit/bin/dxtools.conf
connecting to: tim5230 ( IP/name : tim5230.dcenter.delphix.com )
GET: http://tim5230.dcenter.delphix.com:80/resources/json/delphix/session
** GET http://tim5230.dcenter.delphix.com:80/resources/json/delphix/session ==> 200 OK
Session exists.
GET: http://tim5230.dcenter.delphix.com:80/resources/json/service/configure/currentSystemTime
** GET http://tim5230.dcenter.delphix.com:80/resources/json/service/configure/currentSystemTime ==> 200 OK (1s)
GET: http://tim5230.dcenter.delphix.com:80/resources/json/delphix/action?pageSize=100&pageOffset=0&fromDate=2018-08-24T06%3A00%3A00.000Z
** GET http://tim5230.dcenter.delphix.com:80/resources/json/delphix/action?pageSize=100&pageOffset=0&fromDate=2018-08-24T06%3A00%3A00.000Z ==> 200 OK (1s)

Appliance            StartTime                      State        User or Policy       Type                 Details
-------------------- ------------------------------ ------------ -------------------- -------------------- --------------------------------------------------------------------------------
tim5230              2018-08-24 04:30:00 MDT        FAILED       default snapsync     DB_SYNC              Run SnapSync for database "PDBX2".
tim5230              2018-08-24 04:30:00 MDT        FAILED       default snapsync     DB_SYNC              Run SnapSync for database "PDBX1".

```

As you can see input string "2018-08-24T00:00:00.000Z" was translate into API call 
`action?pageSize=100&pageOffset=0&fromDate=2018-08-24T06%3A00%3A00.000Z`
which should grab data starting from 06:00:00 UTC time as all API calls need UTC timezone.

regards,
Marcin

**Comment by timothyjgorman** [comment]
I don't know why I was so stubborn not to consider that.  Thanks!
