### ISSUE TITLE
Can't connect to v 4.2.4.0 

### ISSUE THREAD

**Issue by dimabarkin** [delphix/dxtoolkit#7]
Trying to connect to one of our old engines v 4.2.4,0 and it fails. Never connected to this engine before with dxtoolkit. with 2nd engine version  5.0.5.3 all works fine.

perl dx_get_users.pl -d namehere -dever 4.2 -debug
Dxtoolkit version 2.3.0-rc1
connecting to: namehere ( IP/name : ipaddress here )
GET: https://ipaddress /resources/json/delphix/session
** GET https://ipaddress:443/resources/json/delphix/session ==> 500 Can't connect to ipaddress :443
Response message: $VAR1 = undef;
$VAR2 = 2;

Can't check session status. Engine dx-eng1-nonprod01 (IP: ipaddress ) could be down.
Can't connect to Dephix Engine dx-eng1-nonprod01

with version  5.0.5.3 all works fine.
ip address and hostname verified.

telnet to ipaddress port 443 resolves ok.

telnet ipaddress  443
Trying ipaddress  ...
Connected to ipaddress .
Escape character is '^]'.
^CConnection closed by foreign host.

Thank you!

**Comment by pioro** [comment]
Hello,

Error 500 mean that Delphix Engine doesn't responded with normal HTTPS respond.
"** GET https://ipaddress:443/resources/json/delphix/session ==> 500 Can't connect to ipaddress :443"

Could you confirm that you can connect to this engine using Delphix GUI or CLI ?

regards,
Marcin

**Comment by dimabarkin** [comment]
Hi Marcin,

Yes, I'm able to connect with gui and cli. only toolkit doesn't operate. We actually never connected with toolkit to this version (4.2.4)
![2016-12-28 10-02-48 am](https://cloud.githubusercontent.com/assets/16688124/21524558/f97a04a2-cce4-11e6-9918-e9f808bfad14.png)
![2016-12-28 10-04-45 am](https://cloud.githubusercontent.com/assets/16688124/21524566/1f1d57a4-cce5-11e6-8619-44a09fa85c65.png)

Regards,
Dmitri

**Comment by pioro** [comment]
Hi,

Thanks for that. 
Some questions:
- are you using source or compiled version ? 
- did you try to run this command (or let say dx_get_applience) without -dever parameter ?
"dever" parameter should be used only if dxtoolkit is not working correctly with new version of Delphix Engine
- did you tried to run dx_logout -d xxxxxx to delete old cookie session ?

regards,
Marcin

**Comment by dimabarkin** [comment]
Hi Marcin,
I'm sending direct email to avoid publishing some details on github.
It is source version (perl). Compiled also gives the same error.Logout doesn't work too. the same error.perl dx_logout.pl -d dx-eng1-nonprod01Can't check session status. Engine dx-eng1-nonprod01 (IP: 10.177.yyyy.yyyy ) could be down.Can't connect to Dephix Engine dx-eng1-nonprod01
(/home/oracle/dxtoolkit-master/bin) $ 
Doesn't work with or without dever flag
Here is the output of dx_get_appliance.pl

(/home/oracle/dxtoolkit-master/bin) $ perl dx_get_appliance.pl -d dx-eng1-nonprod01Can't check session status. Engine dx-eng1-nonprod01 (IP: 10.177.yyy.yy ) could be down.
Appliance            Status   Version  Total (GB) Used (GB)  Free (GB)  PctUsed(%) dSource# VDBs#    Total Ob -------------------- -------- -------- ---------- ---------- ---------- ---------- -------- -------- -------- dx-eng1-nonprod01    DOWN                                                                                     (/home/oracle/dxtoolkit-master/bin) $ 
it works with version 5
(/home/oracle/dxtoolkit-master/bin) $ perl dx_get_appliance.pl -d dx-eng2-nonprod01
Appliance            Status   Version  Total (GB) Used (GB)  Free (GB)  PctUsed(%) dSource# VDBs#    Total Ob -------------------- -------- -------- ---------- ---------- ---------- ---------- -------- -------- -------- dx-eng2-nonprod01    UP       5.0.5.3  9145.00    285.56     8859.44    0.03       3        9        12       


both dx-eng2-nonprod01 and dx-eng1-nonprod01 use https and are in the same subnet.Telnet to port 443 works ok for dx-eng1-nonprod01

able to ssh to dx-eng1-nonprod01 from the same node as dxtoolkit installed.
(/home/oracle/dxtoolkit-master/bin) $ ssh delphix_admin@dx-eng1-nonprod01Password: Last login: Thu Dec  1 21:08:02 2016 from 10.177.YY.YYYYsthaxxxx> version1.5.3sthaxxxx> aboutsthaxxxx about> lsProperties    type: PublicSystemInfo    apiVersion:        type: APIVersion        major: 1        micro: 3        minor: 5    buildTimestamp: 2015-07-07T06:04:24.000Z    buildTitle: Delphix Engine 4.2.4.0    buildVersion:        type: VersionInfo        major: 4        micro: 4        minor: 2        patch: 0    configured: true    currentLocale: en-US    enabledFeatures: XPP    locales: en-US    productName: Delphix Engine    productType: standardsthaxxxx about> 
Thank you,Dmitri 

    On Wednesday, December 28, 2016 11:21 AM, Marcin Przepiorowski <notifications@github.com> wrote:
 

 Hi,Thanks for that.
Some questions:   
   - are you using source or compiled version ?
   - did you try to run this command (or let say dx_get_applience) without -dever parameter ?   
"dever" parameter should be used only if dxtoolkit is not working correctly with new version of Delphix Engine
   - did you tried to run dx_logout -d xxxxxx to delete old cookie session ?
regards,
Marcin—

**Comment by pioro** [comment]
Hi

I afraid you replied to email but it's connected to github. You can delete your entry here 
and send me direct email to marcin@delphix.com.

Please include output from that command 

perl dx_get_appliance.pl -d dx-eng1 -debug 2

regards,
Marcin

**Comment by dimabarkin** [comment]
Works now with newer version of Delphix
