### ISSUE TITLE
dx_get_db_env should be able to filter on RDBMS type

### ISSUE THREAD

**Issue by teaboyteaboy** [delphix/dxtoolkit#73]
For environments where there are multiple database types (Oracle, SQL, ASE, etc.) in groups that many not be consistently named across engines, it would be very helpful to be able to filter on database type in dx_get_db_env.  This would allow for gathering details for all Oracle VDBs on all engines in your environment, for example:

./dx_get_db_env -all -type vdb -rdbms oracle -config

**Comment by pioro** [comment]
added in development branch - will be included in next release
