### ISSUE TITLE
JS contrainer issue

### ISSUE THREAD

**Issue by pioro** [delphix/dxtoolkit#79]
dx_ctl_js_container.exe -d DE -container_name conname -action restore 
-timestamp local_bookmark 

Can't use string ("JS_BRANCH-499") as an ARRAY ref while "strict refs" in use at script/dx_ctl_js_container.pl line 157.

DE: 5.3.1
dxtoolkit: latest

**Comment by pioro** [comment]
Please download a new script from release 2.3.9.2

**Comment by peter-field** [comment]
Hi,

I'm hitting this issue on Solaris 10. Can you please create a Solaris 10 build for this?

oracle@swpddz2:DDPX02 $ /nfs/oradump_dba/delphix/dxtoolkit/2.3.9.1/SunOS/dx_ctl_js_container -action restore -engine dpxdbadev01 -timestamp "2019-03-12 11:00:00" -container_name DDPX02  -fromtemplate -template_name DDPX01
Can't use string ("JS_BRANCH-13") as an ARRAY ref while "strict refs" in use at script/dx_ctl_js_container.pl line 153.

oracle@swpddz2:DDPX02 $ uname -a
SunOS swpddz2 5.10 Generic_150401-64 i86pc i386 i86pc


Thanks

Peter

**Comment by pioro** [comment]
Hi,

Solaris 10 x86 build is ready to download.
https://github.com/delphix/dxtoolkit/releases/tag/v2.3.9.2

regards,
Marcin
