### ISSUE TITLE
Reduce size of compiled Dxtoolkit

### ISSUE THREAD

**Issue by bbalior** [delphix/dxtoolkit#8]
Whole Dxtoolkit has quite a size, which could be greatly reduced by not including the libs sets to every tool. It can be done by for eg.:
- including one binary file combining all necessary libs in dxtoolkit folder, instead adding them to every script.
- Compile whole Dxtoolkit to one executable, specific tools would be called using parameter, for eg. to provision vdb the syntax would look like: 
$ dxtoolkit -provision_vdb <rest of parameters>

That way, the size of the toolkit could be reduced probably to 10-20 MB from few hundred megs.

**Comment by pioro** [comment]
Hi,

When I was looking into that option last time, there was no possibility to do so.
But for sure it's a interesting option to revisit.

regards,
Marcin

**Comment by pioro** [comment]
It's not planned for Perl version of dxtoolkit
