### ISSUE TITLE
dx_ctl_js_container cant restore to shared bookmark if name is used by another bookmark in another template

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/dxtoolkit#80]
Hello,

The issue is that dx_ctl_js_container cant restore to shared bookmark if name is used by another bookmark in another template.

This is the scenario tested:

-Template —> test --> container --> testdc --> source —> D_PDB1 --> bookmark --> testbm1_1 --> shared
-Template --> test --> container --> testdc2 --> source —> D_PDB1 --> bookmark --> testbm2_1 --> shared

-Template --> test2 --> container --> testdc3 --> source —> D_Test11g --> bookmark --> testbm1_1--> shared

These are the couple of test performed:

Test 1 --> To restore testdc2 to testbm1_1 bookmark from same test template from GUI --> Works fine
Test 2 --> To restore testdc2 to testbm1_1 bookmark with dxtoolkit --> Fails with the following error

Problem with job Cannot use bookmark "testbm1_1" with data container "testdc2" since it comes from a different data line
age.
Job for container is not created.

Tested this with dxtoolkit 2.3.9.1 + hot fix 2.3.9.2 :) in Windows.

Can you please help me check it?

Thanks in advance and regards.

**Comment by pioro** [comment]
Hi Carlos,

I have a problem to reproduce this error. What Delphix engine version did you tested ?
This error which you can see is generated by Delphix Engine - not a dxtoolkit.

regards,
Marcin

**Comment by pioro** [comment]
fix committed into develop
