### ISSUE TITLE
Not able to audit for a particular user

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/dxtoolkit#86]
Hello,

When trying to use dx_get_audit command to pull all actions executed by a user, its giving me this error:

bash-4.2$ /home/delphix/dxtoolkit2/dx_get_audit -d delphix5331 -username test
Can't locate object method "getUser" via package "Action_obj" at /tmp/par-64656c70686978/cache-4b8eb44a23dcbe2596d35f377c724a0478512db2/inc/lib/Action_obj.pm line 365.

Tried with latest version in CentOS 7 and MacOS and both throw the same message.

When you have a chance, can you please help me checking it?

Thanks in advance and regards

**Comment by pioro** [comment]
fixed in develop branch - it will be included in next release
