### ISSUE TITLE
Problem with update policy from file ...

### ISSUE THREAD

**Issue by gianpieropiccolo** [delphix/dxtoolkit#89]
I tried with no success the update policies command:

dx_ctl_policy -d $DE_NAME -update -indir $BACKUPDIR/policies

Errors from the dxtoolkit commands:

Updating policy Default Retention from file /sw/dumps/20190517/backup_esedelphix1_20190517_esedelphix1/policies/Default Retention.policy. Update completed
Updating policy Default SnapSync from file /sw/dumps/20190517/backup_esedelphix1_20190517_esedelphix1/policies/Default SnapSync.policy.Problem with update policy from file /sw/
dumps/20190517/backup_esedelphix1_20190517_esedelphix1/policies/Default SnapSync.policy
Updating policy Default Snapshot from file /sw/dumps/20190517/backup_esedelphix1_20190517_esedelphix1/policies/Default Snapshot.policy.Problem with update policy from file /sw/
dumps/20190517/backup_esedelphix1_20190517_esedelphix1/policies/Default Snapshot.policy
Update policies failure

Here https://jmp.sh/gaQqphp the content of the $BACKUPDIR/policies directory.

Best Regards.
Gianpiero

**Comment by gianpieropiccolo** [comment]
Hi, 
did you have a chance to verify my issue? 
I tried the same operation with the latest version of the dxtoolkit just now (release 2.4.0): same behavior.

I'm awaiting for your reply.

Thanks a lot in advance.
Regards.
Gianpiero

**Comment by pioro** [comment]
Hi,

I'm off until next week. I will take a look on it after my return.

Marcin

**Comment by pioro** [comment]
it's committed to development branch and it will be included in next release
