### ISSUE TITLE
warnings in otput of some scripts

### ISSUE THREAD

**Issue by dbarkin** [delphix/dxtoolkit#9]
Error for release 2.3.1:
In release 2.3.0 - it works ok

perl dx_get_users.pl -d Engine

gives an error
Use of implicit split to @_ is deprecated at ../lib/Environment_obj.pm line 1423.

same with 
perl dx_get_db_env.pl -d Engine
Use of implicit split to @_ is deprecated at ../lib/Environment_obj.pm line 1423.

did not test the rest of scripts

**Comment by pioro** [comment]
Hi,

What version of perl are you using ?

Marcin

**Comment by dbarkin** [comment]
$ perl -v

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

Copyright 1987-2009, Larry Wall

**Comment by dbarkin** [comment]
moved to compiled version. Issue is gone.
