### ISSUE TITLE
Allow dx_get_analytics -t all to ignore missing metrics

### ISSUE THREAD

**Issue by ajaytho** [delphix/dxtoolkit#90]
dx_get_analytics always fails if iscisi or nfs is missing. It would be good idea to ignore the missing metric just by stating "data not available for isci/nfs or any other metric". It should still proceed and collect rest of the data. At present it just stop as soon as it detects missing metric. It will be rare for engine to have nfs as well as iscsi on same prod engine

**Comment by pioro** [comment]
Hi,

I think -t all should stop when one metric is not available - as some people are using scripts to extract data and they need to be informed when there is an error.

There is -t standard which is exporting cpu,network,disk and NFS and I can probably add one more for iSCSI like -t windows which will export cpu,disk,iscsi and network ?

Is it OK for you ?

regards,
Marcin

**Comment by ajaytho** [comment]
I think that's better idea to keep std_unix, std_windows so that it handles
iscsi too.

**Comment by pioro** [comment]
The flag will be added to ignore missing metrics

**Comment by pioro** [comment]
Default is to skip a broken analytic but report it by non-zero return code.
There is a new flag -stoponinvalid to stop execution on the invalid analytics
